// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: BasicInformationCluster.xml + globals
// Matter cluster Basic Information Cluster id 0x0028 revision 7
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'CapabilityMinimaStruct'/>
        <see cref = 'Leave'/>
        <see cref = 'LocationDescriptorStruct'/>
        <see cref = 'ProductAppearanceStruct'/>
        <see cref = 'ReachableChanged'/>
        <see cref = 'ShutDown'/>
        <see cref = 'StartUp'/>
    */
    public interface BasicInformation {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Basic Information Cluster" (id 0x0028, revision 7).
        rev 1: Initial revision
        rev 2: Added ProductAppearance attribute
        rev 3: Added SpecificationVersion and MaxPathsPerInvoke attributes
        rev 4: Updated conformance for UniqueID to mandatory
        rev 5: Added ConfigurationVersion attribute as provisional
        rev 6: Added extended information fields to CapabilityMinimaStruct and removed provisional status for
        ConfigurationVersion
        rev 7: Added DeviceLocation attribute
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x28;
            public const string cluster_name = "Basic Information Cluster";
            public const uint revision = 7;
        }

        /**
        Matter enum ColorEnum
        */
        enum ColorEnum {
            /**
            Approximately RGB #000000.
            */
            Black = 0,
            /**
            Approximately RGB #000080.
            */
            Navy = 1,
            /**
            Approximately RGB #008000.
            */
            Green = 2,
            /**
            Approximately RGB #008080.
            */
            Teal = 3,
            /**
            Approximately RGB #800000.
            */
            Maroon = 4,
            /**
            Approximately RGB #800080.
            */
            Purple = 5,
            /**
            Approximately RGB #808000.
            */
            Olive = 6,
            /**
            Approximately RGB #808080.
            */
            Gray = 7,
            /**
            Approximately RGB #0000FF.
            */
            Blue = 8,
            /**
            Approximately RGB #00FF00.
            */
            Lime = 9,
            /**
            Approximately RGB #00FFFF.
            */
            Aqua = 10,
            /**
            Approximately RGB #FF0000.
            */
            Red = 11,
            /**
            Approximately RGB #FF00FF.
            */
            Fuchsia = 12,
            /**
            Approximately RGB #FFFF00.
            */
            Yellow = 13,
            /**
            Approximately RGB #FFFFFF.
            */
            White = 14,
            /**
            Typical hardware "Nickel" color.
            */
            Nickel = 15,
            /**
            Typical hardware "Chrome" color.
            */
            Chrome = 16,
            /**
            Typical hardware "Brass" color.
            */
            Brass = 17,
            /**
            Typical hardware "Copper" color.
            */
            Copper = 18,
            /**
            Typical hardware "Silver" color.
            */
            Silver = 19,
            /**
            Typical hardware "Gold" color.
            */
            Gold = 20,
        }

        /**
        Matter enum ProductFinishEnum
        */
        enum ProductFinishEnum {
            /**
            Product has some other finish not listed below.
            */
            Other = 0,
            /**
            Product has a matte finish.
            */
            Matte = 1,
            /**
            Product has a satin finish.
            */
            Satin = 2,
            /**
            Product has a polished or shiny finish.
            */
            Polished = 3,
            /**
            Product has a rugged finish.
            */
            Rugged = 4,
            /**
            Product has a fabric finish.
            */
            Fabric = 5,
        }

        /**
        Matter struct CapabilityMinimaStruct
        */
        class CapabilityMinimaStruct {
            [MinMax(3, 10000), FieldId(0x0), Default("3"), Constraint("between 3..10000")] ushort CaseSessionsPerFabric;
            [MinMax(3, 10000), FieldId(0x1), Default("3"), Constraint("between 3..10000")] ushort SubscriptionsPerFabric;
            [MinMax(1, 10000), FieldId(0x2), Constraint("between 1..10000"), Conformance("M[(revision>=revision)]")] ushort? SimultaneousInvocationsSupported;
            [MinMax(1, 10000), FieldId(0x3), Constraint("between 1..10000"), Conformance("M[(revision>=revision)]")] ushort? SimultaneousWritesSupported;
            [MinMax(9, 10000), FieldId(0x4), Constraint("between 9..10000"), Conformance("M[(revision>=revision)]")] ushort? ReadPathsSupported;
            [MinMax(3, 10000), FieldId(0x5), Constraint("between 3..10000"), Conformance("M[(revision>=revision)]")] ushort? SubscribePathsSupported;
        }

        /**
        Matter struct ProductAppearanceStruct
        */
        class ProductAppearanceStruct {
            [FieldId(0x0)] ProductFinishEnum Finish;
            [FieldId(0x1), Quality("nullable")] ColorEnum? PrimaryColor;
        }

        /**
        Matter struct LocationDescriptorStruct (from Structs.xml)
        */
        class LocationDescriptorStruct {
            [D(+128), FieldId(0x0), Constraint("maxLength 128")] string LocationName;
            [FieldId(0x1), Quality("nullable")] short? FloorNumber;
            [MatterType("tag"), FieldId(0x2), Quality("nullable")] byte? AreaType;
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [AttrId(0x0), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("desc")] ushort DataModelRevision;
            [D(+32), AttrId(0x1), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("maxLength 32")] string VendorName;
            [MatterType("vendor-id"), AttrId(0x2), Access("read:view"), Quality("fixed"), Default("MS")] ushort VendorID;
            [D(+32), AttrId(0x3), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("maxLength 32")] string ProductName;
            [AttrId(0x4), Access("read:view"), Quality("fixed"), Default("MS")] ushort ProductID;
            [D(+32), AttrId(0x5), Access("read:view write:manage"), Quality("nonVolatile"), Default("\"\""), Constraint("maxLength 32")] string NodeLabel;
            [D(+2), AttrId(0x6), Access("read:view write:admin"), Quality("nonVolatile"), Default("\"XX\""), Constraint("allowed 2")] string Location;
            [AttrId(0x7), Access("read:view"), Quality("fixed"), Default("0")] ushort HardwareVersion;
            [D(+64), AttrId(0x8), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("lengthBetween 1..64")] string HardwareVersionString;
            [AttrId(0x9), Access("read:view"), Quality("fixed"), Default("0"), Constraint("desc")] uint SoftwareVersion;
            [D(+64), AttrId(0xA), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("lengthBetween 1..64")] string SoftwareVersionString;
            [D(+16), AttrId(0xB), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("lengthBetween 8..16"), Conformance("O")] string ManufacturingDate;
            [D(+32), AttrId(0xC), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("maxLength 32"), Conformance("O")] string PartNumber;
            [D(+256), AttrId(0xD), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("maxLength 256"), Conformance("O")] string ProductURL;
            [D(+64), AttrId(0xE), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("maxLength 64"), Conformance("O")] string ProductLabel;
            [D(+32), AttrId(0xF), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("maxLength 32"), Conformance("O")] string SerialNumber;
            [AttrId(0x10), Access("read:view write:manage"), Quality("nonVolatile"), Default("false"), Conformance("O")] bool? LocalConfigDisabled;
            [AttrId(0x11), Access("read:view"), Default("true"), Conformance("O")] bool? Reachable;
            [D(+32), AttrId(0x12), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("maxLength 32"), Conformance("otherwise(M[(revision>=revision)]; O)")] string UniqueID;
            [AttrId(0x13), Access("read:view"), Quality("fixed"), Default("MS")] CapabilityMinimaStruct CapabilityMinima;
            [AttrId(0x14), Access("read:view"), Quality("fixed"), Default("MS"), Conformance("O[(revision>=revision)]")] ProductAppearanceStruct ProductAppearance;
            [AttrId(0x15), Access("read:view"), Quality("fixed"), Default("0"), Constraint("desc"), Conformance("M[(revision>=revision)]")] uint? SpecificationVersion;
            [MinMax(1, 65535), AttrId(0x16), Access("read:view"), Quality("fixed"), Default("1"), Constraint("min 1"), Conformance("M[(revision>=revision)]")] ushort? MaxPathsPerInvoke;
            [AttrId(0x17), Access("read:view write:admin"), Quality("nullable nonVolatile"), Default("MS"), Conformance("otherwise(P; O[(revision>=revision)])")] LocationDescriptorStruct DeviceLocation;
            [MinMax(1, 4294967295), AttrId(0x18), Access("read:view"), Quality("nonVolatile"), Default("1"), Constraint("min 1"), Conformance("M[(revision>=revision)]")] uint? ConfigurationVersion;
        }

        // ═════════════════════════ events ═════════════════════════

        /**
        Matter event StartUp (id 0x00, priority critical)
        */
        class StartUp {
            public const uint event_id = 0x0;
            public const string priority = "critical";
            public const string access = "read:view";
            public const string conformance = "M";
            [FieldId(0x0)] uint SoftwareVersion;
        }

        /**
        Matter event ShutDown (id 0x01, priority critical)
        */
        class ShutDown {
            public const uint event_id = 0x1;
            public const string priority = "critical";
            public const string access = "read:view";
            public const string conformance = "O";
        }

        /**
        Matter event Leave (id 0x02, priority info)
        */
        class Leave {
            public const uint event_id = 0x2;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "O";
            [MatterType("fabric-idx"), MinMax(1, 254), FieldId(0x0), Constraint("between 1..254")] byte FabricIndex;
        }

        /**
        Matter event ReachableChanged (id 0x03, priority info)
        */
        class ReachableChanged {
            public const uint event_id = 0x3;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[attr:Reachable]";
            [FieldId(0x0)] bool ReachableNewValue;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {

            // events (and unreferenced responses) are reported by the server
            [____________r<(StartUp, ShutDown, Leave, ReachableChanged)>]
            struct Report { }

            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
