// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: ColorControl.xml + globals
// Matter cluster Color Control Cluster id 0x0300 revision 10
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'ColorLoopSet'/>
        <see cref = 'EnhancedMoveHue'/>
        <see cref = 'EnhancedMoveToHue'/>
        <see cref = 'EnhancedMoveToHueAndSaturation'/>
        <see cref = 'EnhancedStepHue'/>
        <see cref = 'MoveColor'/>
        <see cref = 'MoveColorTemperature'/>
        <see cref = 'MoveHue'/>
        <see cref = 'MoveSaturation'/>
        <see cref = 'MoveToColor'/>
        <see cref = 'MoveToColorTemperature'/>
        <see cref = 'MoveToHue'/>
        <see cref = 'MoveToHueAndSaturation'/>
        <see cref = 'MoveToSaturation'/>
        <see cref = 'StepColor'/>
        <see cref = 'StepColorTemperature'/>
        <see cref = 'StepHue'/>
        <see cref = 'StepSaturation'/>
        <see cref = 'StopMoveStep'/>
    */
    public interface ColorControl {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Color Control Cluster" (id 0x0300, revision 10).
        rev 1: Mandatory global ClusterRevision attribute added; CCB 2028
        rev 2: Added Options attribute, CCB 2085 2104 2124 2230; ZLO 1.0
        rev 3: CCB 2501 2814 2839 2840 2843 2861
        rev 4: All Hubs changes
        rev 5: New data model format and notation, FeatureMap support
        rev 6: Added clarifications to Scenes support for Matter
        rev 7: Added Q quality for CurrentHue, CurrentSaturation, CurrentX, CurrentY, ColorTemperatureMireds,
        EnhancedCurrentHue and RemainingTime attributes. Added clarifications for behavior related to Step values.
        Added constraints on minimum acceptable color temperature values in mireds.
        rev 8: Change WhitePoint* and ColorPoint* attributes from RW to R (CCB 2490, TCR 11893)
        rev 9: Removed P quality
        rev 10: Added S quality to CurrentHue. Added scene-specific consistency checks for AddScene.
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x300;
            public const string cluster_name = "Color Control Cluster";
            public const uint revision = 10;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            Supports color specification via hue/saturation. (code HS)
            */
            HueSaturation = 1,
            /**
            Enhanced hue is supported. (code EHUE)
            */
            EnhancedHue = 2,
            /**
            Color loop is supported. (code CL)
            */
            ColorLoop = 4,
            /**
            Supports color specification via XY. (code XY)
            */
            XY = 8,
            /**
            Supports specification of color temperature. (code CT)
            */
            ColorTemperature = 16,
        }

        /**
        Matter enum ColorLoopActionEnum
        */
        enum ColorLoopActionEnum {
            /**
            De-activate the color loop.
            */
            Deactivate = 0,
            /**
            Activate the color loop from the value in the ColorLoopStartEnhancedHue field.
            */
            ActivateFromColorLoopStartEnhancedHue = 1,
            /**
            Activate the color loop from the value of the EnhancedCurrentHue attribute.
            */
            ActivateFromEnhancedCurrentHue = 2,
        }

        /**
        Matter enum ColorLoopDirectionEnum
        */
        enum ColorLoopDirectionEnum {
            /**
            Decrement the hue in the color loop.
            */
            Decrement = 0,
            /**
            Increment the hue in the color loop.
            */
            Increment = 1,
        }

        /**
        Matter enum ColorModeEnum
        */
        enum ColorModeEnum {
            /**
            The current hue and saturation attributes determine the color.
            */
            CurrentHueAndCurrentSaturation = 0,
            /**
            The current X and Y attributes determine the color.
            */
            CurrentXAndCurrentY = 1,
            /**
            The color temperature attribute determines the color.
            */
            ColorTemperatureMireds = 2,
        }

        /**
        Matter enum DirectionEnum
        */
        enum DirectionEnum {
            /**
            Shortest distance
            */
            Shortest = 0,
            /**
            Longest distance
            */
            Longest = 1,
            /**
            Up
            */
            Up = 2,
            /**
            Down
            */
            Down = 3,
        }

        /**
        Matter enum DriftCompensationEnum
        */
        enum DriftCompensationEnum {
            /**
            There is no compensation.
            */
            None = 0,
            /**
            The compensation is based on other or unknown mechanism.
            */
            OtherOrUnknown = 1,
            /**
            The compensation is based on temperature monitoring.
            */
            TemperatureMonitoring = 2,
            /**
            The compensation is based on optical luminance monitoring and feedback.
            */
            OpticalLuminanceMonitoringAndFeedback = 3,
            /**
            The compensation is based on optical color monitoring and feedback.
            */
            OpticalColorMonitoringAndFeedback = 4,
        }

        /**
        Matter enum EnhancedColorModeEnum
        */
        enum EnhancedColorModeEnum {
            /**
            The current hue and saturation attributes determine the color.
            */
            CurrentHueAndCurrentSaturation = 0,
            /**
            The current X and Y attributes determine the color.
            */
            CurrentXAndCurrentY = 1,
            /**
            The color temperature attribute determines the color.
            */
            ColorTemperatureMireds = 2,
            /**
            The enhanced current hue and saturation attributes determine the color.
            */
            EnhancedCurrentHueAndCurrentSaturation = 3,
        }

        /**
        Matter enum MoveModeEnum
        */
        enum MoveModeEnum {
            /**
            Stop the movement
            */
            Stop = 0,
            /**
            Move in an upwards direction
            */
            Up = 1,
            /**
            Move in a downwards direction
            */
            Down = 3,
        }

        /**
        Matter enum StepModeEnum
        */
        enum StepModeEnum {
            /**
            Step in an upwards direction
            */
            Up = 1,
            /**
            Step in a downwards direction
            */
            Down = 3,
        }

        /**
        Matter bitmap ColorCapabilitiesBitmap (map8)
        */
        [Flags]
        enum ColorCapabilitiesBitmap {
            /**
            Supports color specification via hue/saturation.
            */
            HueSaturation = 1,
            /**
            Enhanced hue is supported.
            */
            EnhancedHue = 2,
            /**
            Color loop is supported.
            */
            ColorLoop = 4,
            /**
            Supports color specification via XY.
            */
            XY = 8,
            /**
            Supports color specification via color temperature.
            */
            ColorTemperature = 16,
        }

        // bitmap with a single field: AdHoc rejects one-member enums, kept as a constants container
        public struct OptionsBitmap {
            /**
            Dependency on On/Off cluster
            */
            public const ulong ExecuteIfOff = 1;
        }

        /**
        Matter bitmap UpdateFlagsBitmap (map8)
        */
        [Flags]
        enum UpdateFlagsBitmap {
            /**
            Device adheres to the associated action field.
            */
            UpdateAction = 1,
            /**
            Device updates the associated direction attribute.
            */
            UpdateDirection = 2,
            /**
            Device updates the associated time attribute.
            */
            UpdateTime = 4,
            /**
            Device updates the associated start hue attribute.
            */
            UpdateStartHue = 8,
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [MinMax(0, 254), AttrId(0x0), Access("read:view"), Quality("nonVolatile scene quieterReporting"), Constraint("max 254"), Conformance("M[HS]")] byte? CurrentHue;
            [MinMax(0, 254), AttrId(0x1), Access("read:view"), Quality("nonVolatile scene quieterReporting"), Constraint("max 254"), Conformance("M[HS]")] byte? CurrentSaturation;
            [MinMax(0, 65534), AttrId(0x2), Access("read:view"), Quality("quieterReporting"), Default("0"), Constraint("max 65534"), Conformance("O")] ushort? RemainingTime;
            [MinMax(0, 65279), AttrId(0x3), Access("read:view"), Quality("nonVolatile scene quieterReporting"), Constraint("max 65279"), Conformance("M[XY]")] ushort? CurrentX;
            [MinMax(0, 65279), AttrId(0x4), Access("read:view"), Quality("nonVolatile scene quieterReporting"), Constraint("max 65279"), Conformance("M[XY]")] ushort? CurrentY;
            [AttrId(0x5), Access("read:view"), Conformance("O")] DriftCompensationEnum? DriftCompensation;
            [D(+254), AttrId(0x6), Access("read:view"), Constraint("maxLength 254"), Conformance("O")] string CompensationText;
            [MinMax(0, 65279), AttrId(0x7), Access("read:view"), Quality("nonVolatile scene quieterReporting"), Constraint("max 65279"), Conformance("M[CT]")] ushort? ColorTemperatureMireds;
            [AttrId(0x8), Access("read:view"), Quality("nonVolatile")] ColorModeEnum ColorMode;
            [MatterType("OptionsBitmap"), AttrId(0xF), Access("read:view write:operate"), Constraint("desc")] byte Options; // values: constants container OptionsBitmap
            [MinMax(0, 6), AttrId(0x10), Access("read:view"), Quality("nullable fixed"), Constraint("max 6")] byte? NumberOfPrimaries;
            [MinMax(0, 65279), AttrId(0x11), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>0)]; O)")] ushort? Primary1X;
            [MinMax(0, 65279), AttrId(0x12), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>0)]; O)")] ushort? Primary1Y;
            [AttrId(0x13), Access("read:view"), Quality("nullable fixed"), Conformance("otherwise(M[(attr:NumberOfPrimaries>0)]; O)")] byte? Primary1Intensity;
            [MinMax(0, 65279), AttrId(0x15), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>1)]; O)")] ushort? Primary2X;
            [MinMax(0, 65279), AttrId(0x16), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>1)]; O)")] ushort? Primary2Y;
            [AttrId(0x17), Access("read:view"), Quality("nullable fixed"), Conformance("otherwise(M[(attr:NumberOfPrimaries>1)]; O)")] byte? Primary2Intensity;
            [MinMax(0, 65279), AttrId(0x19), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>2)]; O)")] ushort? Primary3X;
            [MinMax(0, 65279), AttrId(0x1A), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>2)]; O)")] ushort? Primary3Y;
            [AttrId(0x1B), Access("read:view"), Quality("nullable fixed"), Conformance("otherwise(M[(attr:NumberOfPrimaries>2)]; O)")] byte? Primary3Intensity;
            [MinMax(0, 65279), AttrId(0x20), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>3)]; O)")] ushort? Primary4X;
            [MinMax(0, 65279), AttrId(0x21), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>3)]; O)")] ushort? Primary4Y;
            [AttrId(0x22), Access("read:view"), Quality("nullable fixed"), Conformance("otherwise(M[(attr:NumberOfPrimaries>3)]; O)")] byte? Primary4Intensity;
            [MinMax(0, 65279), AttrId(0x24), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>4)]; O)")] ushort? Primary5X;
            [MinMax(0, 65279), AttrId(0x25), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>4)]; O)")] ushort? Primary5Y;
            [AttrId(0x26), Access("read:view"), Quality("nullable fixed"), Conformance("otherwise(M[(attr:NumberOfPrimaries>4)]; O)")] byte? Primary5Intensity;
            [MinMax(0, 65279), AttrId(0x28), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>5)]; O)")] ushort? Primary6X;
            [MinMax(0, 65279), AttrId(0x29), Access("read:view"), Quality("fixed"), Constraint("max 65279"), Conformance("otherwise(M[(attr:NumberOfPrimaries>5)]; O)")] ushort? Primary6Y;
            [AttrId(0x2A), Access("read:view"), Quality("nullable fixed"), Conformance("otherwise(M[(attr:NumberOfPrimaries>5)]; O)")] byte? Primary6Intensity;
            [MinMax(0, 65279), AttrId(0x30), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? WhitePointX;
            [MinMax(0, 65279), AttrId(0x31), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? WhitePointY;
            [MinMax(0, 65279), AttrId(0x32), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? ColorPointRX;
            [MinMax(0, 65279), AttrId(0x33), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? ColorPointRY;
            [AttrId(0x34), Access("read:view"), Quality("nullable"), Conformance("O")] byte? ColorPointRIntensity;
            [MinMax(0, 65279), AttrId(0x36), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? ColorPointGX;
            [MinMax(0, 65279), AttrId(0x37), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? ColorPointGY;
            [AttrId(0x38), Access("read:view"), Quality("nullable"), Conformance("O")] byte? ColorPointGIntensity;
            [MinMax(0, 65279), AttrId(0x3A), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? ColorPointBX;
            [MinMax(0, 65279), AttrId(0x3B), Access("read:view"), Constraint("max 65279"), Conformance("O")] ushort? ColorPointBY;
            [AttrId(0x3C), Access("read:view"), Quality("nullable"), Conformance("O")] byte? ColorPointBIntensity;
            [AttrId(0x4000), Access("read:view"), Quality("nonVolatile scene quieterReporting"), Conformance("M[EHUE]")] ushort? EnhancedCurrentHue;
            [AttrId(0x4001), Access("read:view"), Quality("nonVolatile scene")] EnhancedColorModeEnum EnhancedColorMode;
            [MinMax(0, 1), AttrId(0x4002), Access("read:view"), Quality("nonVolatile scene"), Constraint("max 1"), Conformance("M[CL]")] byte? ColorLoopActive;
            [AttrId(0x4003), Access("read:view"), Quality("nonVolatile scene"), Conformance("M[CL]")] ColorLoopDirectionEnum? ColorLoopDirection;
            [AttrId(0x4004), Access("read:view"), Quality("nonVolatile scene"), Conformance("M[CL]")] ushort? ColorLoopTime;
            [AttrId(0x4005), Access("read:view"), Conformance("M[CL]")] ushort? ColorLoopStartEnhancedHue;
            [AttrId(0x4006), Access("read:view"), Conformance("M[CL]")] ushort? ColorLoopStoredEnhancedHue;
            [AttrId(0x400A), Access("read:view"), Constraint("max 0x001F")] ColorCapabilitiesBitmap ColorCapabilities;
            [MinMax(1, 65279), AttrId(0x400B), Access("read:view"), Constraint("between 1..65279"), Conformance("M[CT]")] ushort? ColorTempPhysicalMinMireds;
            [MinMax(0, 65279), AttrId(0x400C), Access("read:view"), Constraint("max 65279"), Conformance("M[CT]")] ushort? ColorTempPhysicalMaxMireds;
            [AttrId(0x400D), Access("read:view"), Constraint("between attr:ColorTempPhysicalMinMireds..attr:ColorTemperatureMireds"), Conformance("M[CT]")] ushort? CoupleColorTempToLevelMinMireds; // bounds depend on another attribute, cannot be bit-packed
            [MinMax(1, 65279), AttrId(0x4010), Access("read:view write:manage"), Quality("nullable nonVolatile"), Constraint("between 1..65279"), Conformance("M[CT]")] ushort? StartUpColorTemperatureMireds;
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) MoveToHue (id 0x00)
        */
        class MoveToHue {
            public const uint command_id = 0x0;
            public const string access = "invoke:operate";
            public const string conformance = "M[HS]";
            [MinMax(0, 254), FieldId(0x0), Constraint("max 254")] byte Hue;
            [FieldId(0x1)] DirectionEnum Direction;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveHue (id 0x01)
        */
        class MoveHue {
            public const uint command_id = 0x1;
            public const string access = "invoke:operate";
            public const string conformance = "M[HS]";
            [FieldId(0x0)] MoveModeEnum MoveMode;
            [FieldId(0x1)] byte Rate;
            [MatterType("OptionsBitmap"), FieldId(0x2), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) StepHue (id 0x02)
        */
        class StepHue {
            public const uint command_id = 0x2;
            public const string access = "invoke:operate";
            public const string conformance = "M[HS]";
            [FieldId(0x0)] StepModeEnum StepMode;
            [FieldId(0x1)] byte StepSize;
            [FieldId(0x2)] byte TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveToSaturation (id 0x03)
        */
        class MoveToSaturation {
            public const uint command_id = 0x3;
            public const string access = "invoke:operate";
            public const string conformance = "M[HS]";
            [MinMax(0, 254), FieldId(0x0), Constraint("max 254")] byte Saturation;
            [MinMax(0, 65534), FieldId(0x1), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x2), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveSaturation (id 0x04)
        */
        class MoveSaturation {
            public const uint command_id = 0x4;
            public const string access = "invoke:operate";
            public const string conformance = "M[HS]";
            [FieldId(0x0)] MoveModeEnum MoveMode;
            [FieldId(0x1)] byte Rate;
            [MatterType("OptionsBitmap"), FieldId(0x2), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) StepSaturation (id 0x05)
        */
        class StepSaturation {
            public const uint command_id = 0x5;
            public const string access = "invoke:operate";
            public const string conformance = "M[HS]";
            [FieldId(0x0)] StepModeEnum StepMode;
            [FieldId(0x1)] byte StepSize;
            [FieldId(0x2)] byte TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveToHueAndSaturation (id 0x06)
        */
        class MoveToHueAndSaturation {
            public const uint command_id = 0x6;
            public const string access = "invoke:operate";
            public const string conformance = "M[HS]";
            [MinMax(0, 254), FieldId(0x0), Constraint("max 254")] byte Hue;
            [MinMax(0, 254), FieldId(0x1), Constraint("max 254")] byte Saturation;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveToColor (id 0x07)
        */
        class MoveToColor {
            public const uint command_id = 0x7;
            public const string access = "invoke:operate";
            public const string conformance = "M[XY]";
            [MinMax(0, 65279), FieldId(0x0), Constraint("max 65279")] ushort ColorX;
            [MinMax(0, 65279), FieldId(0x1), Constraint("max 65279")] ushort ColorY;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveColor (id 0x08)
        */
        class MoveColor {
            public const uint command_id = 0x8;
            public const string access = "invoke:operate";
            public const string conformance = "M[XY]";
            [FieldId(0x0)] short RateX;
            [FieldId(0x1)] short RateY;
            [MatterType("OptionsBitmap"), FieldId(0x2), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) StepColor (id 0x09)
        */
        class StepColor {
            public const uint command_id = 0x9;
            public const string access = "invoke:operate";
            public const string conformance = "M[XY]";
            [FieldId(0x0)] short StepX;
            [FieldId(0x1)] short StepY;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveToColorTemperature (id 0x0A)
        */
        class MoveToColorTemperature {
            public const uint command_id = 0xA;
            public const string access = "invoke:operate";
            public const string conformance = "M[CT]";
            [MinMax(0, 65279), FieldId(0x0), Constraint("max 65279")] ushort ColorTemperatureMireds;
            [MinMax(0, 65534), FieldId(0x1), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x2), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) EnhancedMoveToHue (id 0x40)
        */
        class EnhancedMoveToHue {
            public const uint command_id = 0x40;
            public const string access = "invoke:operate";
            public const string conformance = "M[EHUE]";
            [FieldId(0x0)] ushort EnhancedHue;
            [FieldId(0x1)] DirectionEnum Direction;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) EnhancedMoveHue (id 0x41)
        */
        class EnhancedMoveHue {
            public const uint command_id = 0x41;
            public const string access = "invoke:operate";
            public const string conformance = "M[EHUE]";
            [FieldId(0x0), Constraint("desc")] MoveModeEnum MoveMode;
            [FieldId(0x1)] ushort Rate;
            [MatterType("OptionsBitmap"), FieldId(0x2), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) EnhancedStepHue (id 0x42)
        */
        class EnhancedStepHue {
            public const uint command_id = 0x42;
            public const string access = "invoke:operate";
            public const string conformance = "M[EHUE]";
            [FieldId(0x0), Constraint("desc")] StepModeEnum StepMode;
            [FieldId(0x1)] ushort StepSize;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) EnhancedMoveToHueAndSaturation (id 0x43)
        */
        class EnhancedMoveToHueAndSaturation {
            public const uint command_id = 0x43;
            public const string access = "invoke:operate";
            public const string conformance = "M[EHUE]";
            [FieldId(0x0)] ushort EnhancedHue;
            [MinMax(0, 254), FieldId(0x1), Constraint("max 254")] byte Saturation;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MatterType("OptionsBitmap"), FieldId(0x3), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) ColorLoopSet (id 0x44)
        */
        class ColorLoopSet {
            public const uint command_id = 0x44;
            public const string access = "invoke:operate";
            public const string conformance = "M[CL]";
            [FieldId(0x0)] UpdateFlagsBitmap UpdateFlags;
            [FieldId(0x1)] ColorLoopActionEnum Action;
            [FieldId(0x2)] ColorLoopDirectionEnum Direction;
            [FieldId(0x3)] ushort Time;
            [FieldId(0x4)] ushort StartHue;
            [MatterType("OptionsBitmap"), FieldId(0x5), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x6), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) StopMoveStep (id 0x47)
        */
        class StopMoveStep {
            public const uint command_id = 0x47;
            public const string access = "invoke:operate";
            public const string conformance = "M[(HS|XY|CT)]";
            [MatterType("OptionsBitmap"), FieldId(0x0), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x1), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) MoveColorTemperature (id 0x4B)
        */
        class MoveColorTemperature {
            public const uint command_id = 0x4B;
            public const string access = "invoke:operate";
            public const string conformance = "M[CT]";
            [FieldId(0x0)] MoveModeEnum MoveMode;
            [FieldId(0x1)] ushort Rate;
            [MinMax(0, 65279), FieldId(0x2), Constraint("max 65279")] ushort ColorTemperatureMinimumMireds;
            [MinMax(0, 65279), FieldId(0x3), Constraint("max 65279")] ushort ColorTemperatureMaximumMireds;
            [MatterType("OptionsBitmap"), FieldId(0x4), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x5), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        /**
        Matter command (acknowledged with a status only) StepColorTemperature (id 0x4C)
        */
        class StepColorTemperature {
            public const uint command_id = 0x4C;
            public const string access = "invoke:operate";
            public const string conformance = "M[CT]";
            [FieldId(0x0)] StepModeEnum StepMode;
            [FieldId(0x1)] ushort StepSize;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 65534")] ushort TransitionTime;
            [MinMax(0, 65279), FieldId(0x3), Constraint("max 65279")] ushort ColorTemperatureMinimumMireds;
            [MinMax(0, 65279), FieldId(0x4), Constraint("max 65279")] ushort ColorTemperatureMaximumMireds;
            [MatterType("OptionsBitmap"), FieldId(0x5), Constraint("desc")] byte OptionsMask; // values: constants container OptionsBitmap
            [MatterType("OptionsBitmap"), FieldId(0x6), Constraint("desc")] byte OptionsOverride; // values: constants container OptionsBitmap
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<(MoveToHue, MoveHue, StepHue, MoveToSaturation, MoveSaturation, StepSaturation, MoveToHueAndSaturation, MoveToColor, MoveColor, StepColor, MoveToColorTemperature, EnhancedMoveToHue, EnhancedMoveHue, EnhancedStepHue, EnhancedMoveToHueAndSaturation, ColorLoopSet, StopMoveStep, MoveColorTemperature, StepColorTemperature)>]
            struct Invoke { }


            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
