// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: Descriptor-Cluster.xml + globals
// Matter cluster Descriptor Cluster id 0x001D revision 3
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'DeviceTypeStruct'/>
        <see cref = 'SemanticTagStruct'/>
    */
    public interface Descriptor {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Descriptor Cluster" (id 0x001D, revision 3).
        rev 1: Initial revision
        rev 2: Semantic tag list; TagList feature
        rev 3: Add EndpointUniqueID attribute
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x1D;
            public const string cluster_name = "Descriptor Cluster";
            public const uint revision = 3;
        }

        // single feature: AdHoc rejects one-member enums, kept as a constants container
        public struct Features {
            /**
            The TagList attribute is present (code TAGLIST)
            */
            public const uint TagList = 1;
        }

        /**
        Matter struct DeviceTypeStruct
        */
        class DeviceTypeStruct {
            [MatterType("devtype-id"), FieldId(0x0)] uint DeviceType;
            [MinMax(1, 65535), FieldId(0x1), Constraint("min 1")] ushort Revision;
        }

        /**
        Matter struct SemanticTagStruct (from Structs.xml)
        */
        class SemanticTagStruct {
            [MatterType("vendor-id"), FieldId(0x0), Quality("nullable"), Default("null")] ushort? MfgCode;
            [MatterType("namespace"), FieldId(0x1)] byte NamespaceID;
            [MatterType("tag"), FieldId(0x2)] byte Tag;
            [D(+64), FieldId(0x3), Quality("nullable"), Default("null"), Constraint("maxLength 64"), Conformance("otherwise(M[(field:MfgCode!=null)]; O)")] string Label;
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [MatterType("list<DeviceTypeStruct>"), AttrId(0x0), Access("read:view"), Quality("fixed"), Default("desc"), Constraint("minCount 1")] DeviceTypeStruct[,,] DeviceTypeList;
            [MatterType("list<cluster-id>"), AttrId(0x1), Access("read:view"), Quality("fixed"), Default("empty")] uint[,,] ServerList;
            [MatterType("list<cluster-id>"), AttrId(0x2), Access("read:view"), Quality("fixed"), Default("empty")] uint[,,] ClientList;
            [MatterType("list<endpoint-no>"), AttrId(0x3), Access("read:view"), Default("empty")] ushort[,,] PartsList;
            [D(6), MatterType("list<SemanticTagStruct>"), AttrId(0x4), Access("read:view"), Quality("fixed"), Default("MS"), Constraint("countBetween 1..6"), Conformance("M[TAGLIST]")] SemanticTagStruct[,,] TagList;
            [D(+32), AttrId(0x5), Access("read:view"), Quality("fixed"), Constraint("maxLength 32"), Conformance("O")] string EndpointUniqueID;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {

            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
