// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: DoorLock.xml + globals
// Matter cluster Door Lock Cluster id 0x0101 revision 10
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'ClearAliroReaderConfig'/>
        <see cref = 'ClearCredential'/>
        <see cref = 'ClearHolidaySchedule'/>
        <see cref = 'ClearUser'/>
        <see cref = 'ClearWeekDaySchedule'/>
        <see cref = 'ClearYearDaySchedule'/>
        <see cref = 'CredentialStruct'/>
        <see cref = 'DoorLockAlarm'/>
        <see cref = 'DoorStateChange'/>
        <see cref = 'GetCredentialStatusRequest'/>
        <see cref = 'GetCredentialStatusResponse'/>
        <see cref = 'GetHolidayScheduleRequest'/>
        <see cref = 'GetHolidayScheduleResponse'/>
        <see cref = 'GetUserRequest'/>
        <see cref = 'GetUserResponse'/>
        <see cref = 'GetWeekDayScheduleRequest'/>
        <see cref = 'GetWeekDayScheduleResponse'/>
        <see cref = 'GetYearDayScheduleRequest'/>
        <see cref = 'GetYearDayScheduleResponse'/>
        <see cref = 'LockDoor'/>
        <see cref = 'LockOperation'/>
        <see cref = 'LockOperationError'/>
        <see cref = 'LockUserChange'/>
        <see cref = 'SetAliroReaderConfig'/>
        <see cref = 'SetCredentialRequest'/>
        <see cref = 'SetCredentialResponse'/>
        <see cref = 'SetHolidaySchedule'/>
        <see cref = 'SetUser'/>
        <see cref = 'SetWeekDaySchedule'/>
        <see cref = 'SetYearDaySchedule'/>
        <see cref = 'UnboltDoor'/>
        <see cref = 'UnlockDoor'/>
        <see cref = 'UnlockWithTimeout'/>
        <see cref = 'octstr_max_2'/>
    */
    public interface DoorLock {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Door Lock Cluster" (id 0x0101, revision 10).
        rev 1: Mandatory global ClusterRevision attribute added; CCB 1811 1812 1821
        rev 2: CCB 2430
        rev 3: CCB 2629 2630
        rev 4: All Hubs changes and added feature map
        rev 5: CCB 3472 3474 3338
        rev 6: New data model format and notation. Added User features. General cleanup of functionality
        rev 7: Added support for European door locks (unbolt feature)
        rev 8: Removed LOG and NOT feature, fixed constraints on NumberOf*Schedules attributes and added support for
        Aliro credential provisioning
        rev 9: Removed AlarmMask attribute
        rev 10: Removed Zigbee related elements and P quality
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x101;
            public const string cluster_name = "Door Lock Cluster";
            public const uint revision = 10;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            Lock supports PIN credentials (via keypad, or over-the-air) (code PIN)
            */
            PINCredential = 1,
            /**
            Lock supports RFID credentials (code RID)
            */
            RFIDCredential = 2,
            /**
            Lock supports finger related credentials (fingerprint, finger vein) (code FGP)
            */
            FingerCredentials = 4,
            /**
            (code LOG)
            */
            Logging = 8,
            /**
            Lock supports week day user access schedules (code WDSCH)
            */
            WeekDayAccessSchedules = 16,
            /**
            Lock supports a door position sensor that indicates door's state (code DPS)
            */
            DoorPositionSensor = 32,
            /**
            Lock supports face related credentials (face, iris, retina) (code FACE)
            */
            FaceCredentials = 64,
            /**
            PIN codes over-the-air supported for lock/unlock operations (code COTA)
            */
            CredentialOverTheAirAccess = 128,
            /**
            Lock supports the user commands and database (code USR)
            */
            User = 256,
            /**
            (code NOT)
            */
            Notification = 512,
            /**
            Lock supports year day user access schedules (code YDSCH)
            */
            YearDayAccessSchedules = 1024,
            /**
            Lock supports holiday schedules (code HDSCH)
            */
            HolidaySchedules = 2048,
            /**
            Lock supports unbolting (code UBOLT)
            */
            Unbolting = 4096,
            /**
            Lock supports Aliro credential provisioning as defined in Aliro (code ALIRO)
            */
            AliroProvisioning = 8192,
            /**
            Lock supports the Bluetooth LE + UWB Access Control Flow as defined in Aliro (code ALBU)
            */
            AliroBLEUWB = 16384,
        }

        /**
        Matter enum AlarmCodeEnum
        */
        enum AlarmCodeEnum {
            /**
            Locking Mechanism Jammed
            */
            LockJammed = 0,
            /**
            Lock Reset to Factory Defaults
            */
            LockFactoryReset = 1,
            /**
            Lock Radio Power Cycled
            */
            LockRadioPowerCycled = 3,
            /**
            Tamper Alarm - wrong code entry limit
            */
            WrongCodeEntryLimit = 4,
            /**
            Tamper Alarm - front escutcheon removed from main
            */
            FrontEsceutcheonRemoved = 5,
            /**
            Forced Door Open under Door Locked Condition
            */
            DoorForcedOpen = 6,
            /**
            Door ajar
            */
            DoorAjar = 7,
            /**
            Force User SOS alarm
            */
            ForcedUser = 8,
        }

        /**
        Matter enum CredentialRuleEnum
        */
        enum CredentialRuleEnum {
            /**
            Only one credential is required for lock operation
            */
            Single = 0,
            /**
            Any two credentials are required for lock operation
            */
            Dual = 1,
            /**
            Any three credentials are required for lock operation
            */
            Tri = 2,
        }

        /**
        Matter enum CredentialTypeEnum
        */
        enum CredentialTypeEnum {
            /**
            Programming PIN code credential type
            */
            ProgrammingPIN = 0,
            /**
            PIN code credential type
            */
            PIN = 1,
            /**
            RFID identifier credential type
            */
            RFID = 2,
            /**
            Fingerprint identifier credential type
            */
            Fingerprint = 3,
            /**
            Finger vein identifier credential type
            */
            FingerVein = 4,
            /**
            Face identifier credential type
            */
            Face = 5,
            /**
            A Credential Issuer public key as defined in Aliro
            */
            AliroCredentialIssuerKey = 6,
            /**
            An Endpoint public key as defined in Aliro which can be evicted if space is needed for another endpoint key
            */
            AliroEvictableEndpointKey = 7,
            /**
            An Endpoint public key as defined in Aliro which cannot be evicted if space is needed for another endpoint key
            */
            AliroNonEvictableEndpointKey = 8,
        }

        /**
        Matter enum DataOperationTypeEnum
        */
        enum DataOperationTypeEnum {
            /**
            Data is being added or was added
            */
            Add = 0,
            /**
            Data is being cleared or was cleared
            */
            Clear = 1,
            /**
            Data is being modified or was modified
            */
            Modify = 2,
        }

        /**
        Matter enum DoorStateEnum
        */
        enum DoorStateEnum {
            /**
            Door state is open
            */
            DoorOpen = 0,
            /**
            Door state is closed
            */
            DoorClosed = 1,
            /**
            Door state is jammed
            */
            DoorJammed = 2,
            /**
            Door state is currently forced open
            */
            DoorForcedOpen = 3,
            /**
            Door state is invalid for unspecified reason
            */
            DoorUnspecifiedError = 4,
            /**
            Door state is ajar
            */
            DoorAjar = 5,
        }

        /**
        Matter enum EventTypeEnum
        */
        enum EventTypeEnum {
            /**
            Event type is operation
            */
            Operation = 0,
            /**
            Event type is programming
            */
            Programming = 1,
            /**
            Event type is alarm
            */
            Alarm = 2,
        }

        /**
        Matter enum LEDSettingEnum
        */
        enum LEDSettingEnum {
            /**
            Never use LED for signalization
            */
            NoLEDSignal = 0,
            /**
            Use LED signalization except for access allowed events
            */
            NoLEDSignalAccessAllowed = 1,
            /**
            Use LED signalization for all events
            */
            LEDSignalAll = 2,
        }

        /**
        Matter enum LockDataTypeEnum
        */
        enum LockDataTypeEnum {
            /**
            Unspecified or manufacturer specific lock user data added, cleared, or modified.
            */
            Unspecified = 0,
            /**
            Lock programming PIN code was added, cleared, or modified.
            */
            ProgrammingCode = 1,
            /**
            Lock user index was added, cleared, or modified.
            */
            UserIndex = 2,
            /**
            Lock user week day schedule was added, cleared, or modified.
            */
            WeekDaySchedule = 3,
            /**
            Lock user year day schedule was added, cleared, or modified.
            */
            YearDaySchedule = 4,
            /**
            Lock holiday schedule was added, cleared, or modified.
            */
            HolidaySchedule = 5,
            /**
            Lock user PIN code was added, cleared, or modified.
            */
            PIN = 6,
            /**
            Lock user RFID code was added, cleared, or modified.
            */
            RFID = 7,
            /**
            Lock user fingerprint was added, cleared, or modified.
            */
            Fingerprint = 8,
            /**
            Lock user finger-vein information was added, cleared, or modified.
            */
            FingerVein = 9,
            /**
            Lock user face information was added, cleared, or modified.
            */
            Face = 10,
            /**
            An Aliro credential issuer key credential was added, cleared, or modified.
            */
            AliroCredentialIssuerKey = 11,
            /**
            An Aliro endpoint key credential which can be evicted credential was added, cleared, or modified.
            */
            AliroEvictableEndpointKey = 12,
            /**
            An Aliro endpoint key credential which cannot be evicted was added, cleared, or modified.
            */
            AliroNonEvictableEndpointKey = 13,
        }

        /**
        Matter enum LockOperationTypeEnum
        */
        enum LockOperationTypeEnum {
            /**
            Lock operation
            */
            Lock = 0,
            /**
            Unlock operation
            */
            Unlock = 1,
            /**
            Triggered by keypad entry for user with User Type set to Non Access User
            */
            NonAccessUserEvent = 2,
            /**
            Triggered by using a user with UserType set to Forced User
            */
            ForcedUserEvent = 3,
            /**
            Unlatch operation
            */
            Unlatch = 4,
        }

        /**
        Matter enum LockStateEnum
        */
        enum LockStateEnum {
            /**
            Lock state is not fully locked
            */
            NotFullyLocked = 0,
            /**
            Lock state is fully locked
            */
            Locked = 1,
            /**
            Lock state is fully unlocked
            */
            Unlocked = 2,
            /**
            Lock state is fully unlocked and the latch is pulled
            */
            Unlatched = 3,
        }

        /**
        Matter enum LockTypeEnum
        */
        enum LockTypeEnum {
            /**
            Physical lock type is dead bolt
            */
            DeadBolt = 0,
            /**
            Physical lock type is magnetic
            */
            Magnetic = 1,
            /**
            Physical lock type is other
            */
            Other = 2,
            /**
            Physical lock type is mortise
            */
            Mortise = 3,
            /**
            Physical lock type is rim
            */
            Rim = 4,
            /**
            Physical lock type is latch bolt
            */
            LatchBolt = 5,
            /**
            Physical lock type is cylindrical lock
            */
            CylindricalLock = 6,
            /**
            Physical lock type is tubular lock
            */
            TubularLock = 7,
            /**
            Physical lock type is interconnected lock
            */
            InterconnectedLock = 8,
            /**
            Physical lock type is dead latch
            */
            DeadLatch = 9,
            /**
            Physical lock type is door furniture
            */
            DoorFurniture = 10,
            /**
            Physical lock type is euro cylinder
            */
            Eurocylinder = 11,
        }

        /**
        Matter enum OperatingModeEnum
        */
        enum OperatingModeEnum {
            Normal = 0,
            Vacation = 1,
            Privacy = 2,
            NoRemoteLockUnlock = 3,
            Passage = 4,
        }

        /**
        Matter enum OperationErrorEnum
        */
        enum OperationErrorEnum {
            /**
            Lock/unlock error caused by unknown or unspecified source
            */
            Unspecified = 0,
            /**
            Lock/unlock error caused by invalid PIN, RFID, fingerprint or other credential
            */
            InvalidCredential = 1,
            /**
            Lock/unlock error caused by disabled USER or credential
            */
            DisabledUserDenied = 2,
            /**
            Lock/unlock error caused by schedule restriction
            */
            Restricted = 3,
            /**
            Lock/unlock error caused by insufficient battery power left to safely actuate the lock
            */
            InsufficientBattery = 4,
        }

        /**
        Matter enum OperationSourceEnum
        */
        enum OperationSourceEnum {
            /**
            Lock/unlock operation came from unspecified source
            */
            Unspecified = 0,
            /**
            Lock/unlock operation came from manual operation (key, thumbturn, handle, etc).
            */
            Manual = 1,
            /**
            Lock/unlock operation came from proprietary remote source (e.g. vendor app/cloud)
            */
            ProprietaryRemote = 2,
            /**
            Lock/unlock operation came from keypad
            */
            Keypad = 3,
            /**
            Lock/unlock operation came from lock automatically (e.g. relock timer)
            */
            Auto = 4,
            /**
            Lock/unlock operation came from lock button (e.g. one touch or button)
            */
            Button = 5,
            /**
            Lock/unlock operation came from lock due to a schedule
            */
            Schedule = 6,
            /**
            Lock/unlock operation came from remote node
            */
            Remote = 7,
            /**
            Lock/unlock operation came from RFID card
            */
            RFID = 8,
            /**
            Lock/unlock operation came from biometric source (e.g. face, fingerprint/fingervein)
            */
            Biometric = 9,
            /**
            Lock/unlock operation came from an interaction defined in Aliro, or user change operation was a step-up
            credential provisioning as defined in Aliro
            */
            Aliro = 10,
        }

        /**
        Matter enum SoundVolumeEnum
        */
        enum SoundVolumeEnum {
            /**
            Silent Mode
            */
            Silent = 0,
            /**
            Low Volume
            */
            Low = 1,
            /**
            High Volume
            */
            High = 2,
            /**
            Medium Volume
            */
            Medium = 3,
        }

        /**
        Matter enum StatusCodeEnum
        */
        enum StatusCodeEnum {
            /**
            Entry would cause a duplicate credential/ID.
            */
            Duplicate = 0x02,
            /**
            Entry would replace an occupied slot.
            */
            Occupied = 0x03,
        }

        /**
        Matter enum UserStatusEnum
        */
        enum UserStatusEnum {
            /**
            The user ID is available
            */
            Available = 0,
            /**
            The user ID is occupied and enabled
            */
            OccupiedEnabled = 1,
            /**
            The user ID is occupied and disabled
            */
            OccupiedDisabled = 3,
        }

        /**
        Matter enum UserTypeEnum
        */
        enum UserTypeEnum {
            /**
            The user ID type is unrestricted
            */
            UnrestrictedUser = 0,
            /**
            The user ID type is schedule
            */
            YearDayScheduleUser = 1,
            /**
            The user ID type is schedule
            */
            WeekDayScheduleUser = 2,
            /**
            The user ID type is programming
            */
            ProgrammingUser = 3,
            /**
            The user ID type is non access
            */
            NonAccessUser = 4,
            /**
            The user ID type is forced
            */
            ForcedUser = 5,
            /**
            The user ID type is disposable
            */
            DisposableUser = 6,
            /**
            The user ID type is expiring
            */
            ExpiringUser = 7,
            /**
            The user ID type is schedule restricted
            */
            ScheduleRestrictedUser = 8,
            /**
            The user ID type is remote only
            */
            RemoteOnlyUser = 9,
        }

        /**
        Matter bitmap ConfigurationRegisterBitmap (map8)
        */
        [Flags]
        enum ConfigurationRegisterBitmap {
            /**
            The state of local programming functionality
            */
            LocalProgramming = 1,
            /**
            The state of the keypad interface
            */
            KeypadInterface = 2,
            /**
            The state of the remote interface
            */
            RemoteInterface = 4,
            /**
            Sound volume is set to Silent value
            */
            SoundVolume = 32,
            /**
            Auto relock time it set to 0
            */
            AutoRelockTime = 64,
            /**
            LEDs is disabled
            */
            LEDSettings = 128,
        }

        /**
        Matter bitmap CredentialRulesBitmap (map8)
        */
        [Flags]
        enum CredentialRulesBitmap {
            /**
            Only one credential is required for lock operation
            */
            Single = 1,
            /**
            Any two credentials are required for lock operation
            */
            Dual = 2,
            /**
            Any three credentials are required for lock operation
            */
            Tri = 4,
        }

        /**
        Matter bitmap DaysMaskBitmap (map8)
        */
        [Flags]
        enum DaysMaskBitmap {
            /**
            Schedule is applied on Sunday
            */
            Sunday = 1,
            /**
            Schedule is applied on Monday
            */
            Monday = 2,
            /**
            Schedule is applied on Tuesday
            */
            Tuesday = 4,
            /**
            Schedule is applied on Wednesday
            */
            Wednesday = 8,
            /**
            Schedule is applied on Thursday
            */
            Thursday = 16,
            /**
            Schedule is applied on Friday
            */
            Friday = 32,
            /**
            Schedule is applied on Saturday
            */
            Saturday = 64,
        }

        /**
        Matter bitmap LocalProgrammingFeaturesBitmap (map8)
        */
        [Flags]
        enum LocalProgrammingFeaturesBitmap {
            /**
            The state of the ability to add users, credentials or schedules on the device
            */
            AddUsersCredentialsSchedules = 1,
            /**
            The state of the ability to modify users, credentials or schedules on the device
            */
            ModifyUsersCredentialsSchedules = 2,
            /**
            The state of the ability to clear users, credentials or schedules on the device
            */
            ClearUsersCredentialsSchedules = 4,
            /**
            The state of the ability to adjust settings on the device
            */
            AdjustSettings = 8,
        }

        /**
        Matter bitmap OperatingModesBitmap (map8)
        */
        [Flags]
        enum OperatingModesBitmap {
            /**
            Normal operation mode
            */
            Normal = 1,
            /**
            Vacation operation mode
            */
            Vacation = 2,
            /**
            Privacy operation mode
            */
            Privacy = 4,
            /**
            No remote lock and unlock operation mode
            */
            NoRemoteLockUnlock = 8,
            /**
            Passage operation mode
            */
            Passage = 16,
        }

        /**
        Matter struct CredentialStruct
        */
        class CredentialStruct {
            [FieldId(0x0)] CredentialTypeEnum CredentialType;
            [FieldId(0x1)] ushort CredentialIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        // octet string of up to 2 bytes, item type of list<octstr> fields
        class octstr_max_2 { [D(2)] Binary[,,] bytes; }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [AttrId(0x0), Access("read:view"), Quality("nullable"), Constraint("desc")] LockStateEnum? LockState;
            [AttrId(0x1), Access("read:view"), Constraint("desc")] LockTypeEnum LockType;
            [AttrId(0x2), Access("read:view")] bool ActuatorEnabled;
            [AttrId(0x3), Access("read:view"), Quality("nullable"), Constraint("desc"), Conformance("M[DPS]")] DoorStateEnum? DoorState;
            [AttrId(0x4), Access("read:view write:manage"), Conformance("O[DPS]")] uint? DoorOpenEvents;
            [AttrId(0x5), Access("read:view write:manage"), Conformance("O[DPS]")] uint? DoorClosedEvents;
            [AttrId(0x6), Access("read:view write:manage"), Conformance("O[DPS]")] ushort? OpenPeriod;
            [AttrId(0x11), Access("read:view"), Quality("fixed"), Conformance("M[USR]")] ushort? NumberOfTotalUsersSupported; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [AttrId(0x12), Access("read:view"), Quality("fixed"), Conformance("M[PIN]")] ushort? NumberOfPINUsersSupported; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [AttrId(0x13), Access("read:view"), Quality("fixed"), Conformance("M[RID]")] ushort? NumberOfRFIDUsersSupported; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [MinMax(0, 253), AttrId(0x14), Access("read:view"), Quality("fixed"), Constraint("max 0xFD"), Conformance("M[WDSCH]")] byte? NumberOfWeekDaySchedulesSupportedPerUser;
            [MinMax(0, 253), AttrId(0x15), Access("read:view"), Quality("fixed"), Constraint("max 0xFD"), Conformance("M[YDSCH]")] byte? NumberOfYearDaySchedulesSupportedPerUser;
            [MinMax(0, 253), AttrId(0x16), Access("read:view"), Quality("fixed"), Constraint("max 0xFD"), Conformance("M[HDSCH]")] byte? NumberOfHolidaySchedulesSupported;
            [AttrId(0x17), Access("read:view"), Quality("fixed"), Conformance("M[PIN]")] byte? MaxPINCodeLength;
            [AttrId(0x18), Access("read:view"), Quality("fixed"), Conformance("M[PIN]")] byte? MinPINCodeLength;
            [AttrId(0x19), Access("read:view"), Quality("fixed"), Conformance("M[RID]")] byte? MaxRFIDCodeLength;
            [AttrId(0x1A), Access("read:view"), Quality("fixed"), Conformance("M[RID]")] byte? MinRFIDCodeLength;
            [AttrId(0x1B), Access("read:view"), Quality("fixed"), Conformance("M[USR]")] CredentialRulesBitmap? CredentialRulesSupport;
            [AttrId(0x1C), Access("read:view"), Quality("fixed"), Conformance("M[USR]")] byte? NumberOfCredentialsSupportedPerUser;
            [D(+3), AttrId(0x21), Access("read:view write?:manage"), Default("MS"), Constraint("maxLength 3"), Conformance("O")] string Language;
            [AttrId(0x22), Access("read:view write?:manage"), Default("0"), Conformance("O")] LEDSettingEnum? LEDSettings;
            [AttrId(0x23), Access("read:view write?:manage"), Default("MS"), Conformance("O")] uint? AutoRelockTime;
            [AttrId(0x24), Access("read:view write?:manage"), Default("0"), Conformance("O")] SoundVolumeEnum? SoundVolume;
            [AttrId(0x25), Access("read:view write?:manage"), Constraint("desc")] OperatingModeEnum OperatingMode;
            [AttrId(0x26), Access("read:view"), Quality("fixed")] OperatingModesBitmap SupportedOperatingModes;
            [AttrId(0x27), Access("read:view"), Default("0"), Conformance("O")] ConfigurationRegisterBitmap? DefaultConfigurationRegister;
            [AttrId(0x28), Access("read:view write?:admin"), Default("true"), Conformance("O")] bool? EnableLocalProgramming;
            [AttrId(0x29), Access("read:view write:manage"), Default("false"), Conformance("O")] bool? EnableOneTouchLocking;
            [AttrId(0x2A), Access("read:view write:manage"), Default("false"), Conformance("O")] bool? EnableInsideStatusLED;
            [AttrId(0x2B), Access("read:view write:manage"), Default("false"), Conformance("O")] bool? EnablePrivacyModeButton;
            [AttrId(0x2C), Access("read:view write?:admin"), Default("0"), Conformance("O")] LocalProgrammingFeaturesBitmap? LocalProgrammingFeatures;
            [MinMax(1, 255), AttrId(0x30), Access("read:view write?:admin"), Constraint("between 1..255"), Conformance("M[(PIN|RID)]")] byte? WrongCodeEntryLimit;
            [MinMax(1, 255), AttrId(0x31), Access("read:view write?:admin"), Constraint("between 1..255"), Conformance("M[(PIN|RID)]")] byte? UserCodeTemporaryDisableTime;
            [AttrId(0x32), Access("read:view write?:admin"), Default("false"), Conformance("O[(!USR&PIN)]")] bool? SendPINOverTheAir;
            [AttrId(0x33), Access("read:view write?:admin"), Conformance("M[(COTA&PIN)]")] bool? RequirePINforRemoteOperation;
            [MinMax(1, 2880), AttrId(0x35), Access("read:view write?:admin"), Default("MS"), Constraint("between 1..2880"), Conformance("O[USR]")] ushort? ExpiringUserTimeout;
            [D(65), AttrId(0x80), Access("read:admin"), Quality("nullable"), Constraint("allowed 65"), Conformance("M[ALIRO]")] Binary[,,] AliroReaderVerificationKey;
            [D(16), AttrId(0x81), Access("read:admin"), Quality("nullable"), Constraint("allowed 16"), Conformance("M[ALIRO]")] Binary[,,] AliroReaderGroupIdentifier;
            [D(16), AttrId(0x82), Access("read:admin"), Quality("fixed"), Constraint("allowed 16"), Conformance("M[ALIRO]")] Binary[,,] AliroReaderGroupSubIdentifier;
            [D(16), MatterType("list<octstr>"), AttrId(0x83), Access("read:admin"), Quality("fixed"), Constraint("maxCount 16"), Conformance("M[ALIRO]")] octstr_max_2[,,] AliroExpeditedTransactionSupportedProtocolVersions; // entry constraint: allowed 2
            [D(16), AttrId(0x84), Access("read:admin"), Quality("nullable"), Constraint("allowed 16"), Conformance("M[ALBU]")] Binary[,,] AliroGroupResolvingKey;
            [D(16), MatterType("list<octstr>"), AttrId(0x85), Access("read:admin"), Quality("fixed"), Constraint("maxCount 16"), Conformance("M[ALBU]")] octstr_max_2[,,] AliroSupportedBLEUWBProtocolVersions; // entry constraint: allowed 2
            [AttrId(0x86), Access("read:admin"), Quality("fixed"), Conformance("M[ALBU]")] byte? AliroBLEAdvertisingVersion;
            [AttrId(0x87), Access("read:view"), Quality("fixed"), Conformance("M[ALIRO]")] ushort? NumberOfAliroCredentialIssuerKeysSupported; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [AttrId(0x88), Access("read:view"), Quality("fixed"), Conformance("M[ALIRO]")] ushort? NumberOfAliroEndpointKeysSupported; // physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) LockDoor (id 0x00)
        */
        class LockDoor {
            public const uint command_id = 0x0;
            public const string access = "invoke:operate timed";
            public const string conformance = "M";
            [FieldId(0x0), Conformance("O[(COTA&PIN)]")] Binary[,,] PINCode;
        }

        /**
        Matter command (acknowledged with a status only) UnlockDoor (id 0x01)
        */
        class UnlockDoor {
            public const uint command_id = 0x1;
            public const string access = "invoke:operate timed";
            public const string conformance = "M";
            [FieldId(0x0), Conformance("O[(COTA&PIN)]")] Binary[,,] PINCode;
        }

        /**
        Matter command (acknowledged with a status only) UnlockWithTimeout (id 0x03)
        */
        class UnlockWithTimeout {
            public const uint command_id = 0x3;
            public const string access = "invoke:operate timed";
            public const string conformance = "O";
            [FieldId(0x0)] ushort Timeout;
            [FieldId(0x1), Conformance("O[(COTA&PIN)]")] Binary[,,] PINCode;
        }

        /**
        Matter command (acknowledged with a status only) SetWeekDaySchedule (id 0x0B)
        */
        class SetWeekDaySchedule {
            public const uint command_id = 0xB;
            public const string access = "invoke:admin";
            public const string conformance = "M[WDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfWeekDaySchedulesSupportedPerUser")] byte WeekDayIndex; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [FieldId(0x2)] DaysMaskBitmap DaysMask;
            [MinMax(0, 23), FieldId(0x3), Constraint("max 23")] byte StartHour;
            [MinMax(0, 59), FieldId(0x4), Constraint("max 59")] byte StartMinute;
            [MinMax(0, 23), FieldId(0x5), Constraint("max 23")] byte EndHour;
            [MinMax(0, 59), FieldId(0x6), Constraint("max 59")] byte EndMinute;
        }

        /**
        Matter request, answered by GetWeekDayScheduleResponse GetWeekDaySchedule (id 0x0C)
        */
        class GetWeekDayScheduleRequest {
            public const uint command_id = 0xC;
            public const string access = "invoke:admin";
            public const string conformance = "M[WDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfWeekDaySchedulesSupportedPerUser")] byte WeekDayIndex; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter response GetWeekDayScheduleResponse (id 0x0C)
        */
        class GetWeekDayScheduleResponse {
            public const uint command_id = 0xC;
            public const string conformance = "M[WDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfWeekDaySchedulesSupportedPerUser")] byte WeekDayIndex; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [MatterType("enum8"), FieldId(0x2), Constraint("desc")] byte Status;
            [FieldId(0x3), Conformance("O")] DaysMaskBitmap? DaysMask;
            [MinMax(0, 23), FieldId(0x4), Constraint("max 23"), Conformance("O")] byte? StartHour;
            [MinMax(0, 59), FieldId(0x5), Constraint("max 59"), Conformance("O")] byte? StartMinute;
            [MinMax(0, 23), FieldId(0x6), Constraint("max 23"), Conformance("O")] byte? EndHour;
            [MinMax(0, 59), FieldId(0x7), Constraint("max 59"), Conformance("O")] byte? EndMinute;
        }

        /**
        Matter command (acknowledged with a status only) ClearWeekDaySchedule (id 0x0D)
        */
        class ClearWeekDaySchedule {
            public const uint command_id = 0xD;
            public const string access = "invoke:admin";
            public const string conformance = "M[WDSCH]";
            [FieldId(0x0), Constraint("allowed 0xFE")] byte WeekDayIndex;
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter command (acknowledged with a status only) SetYearDaySchedule (id 0x0E)
        */
        class SetYearDaySchedule {
            public const uint command_id = 0xE;
            public const string access = "invoke:admin";
            public const string conformance = "M[YDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfYearDaySchedulesSupportedPerUser")] byte YearDayIndex; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [FieldId(0x2)] DateTime LocalStartTime; // Matter epoch-s
            [FieldId(0x3)] DateTime LocalEndTime; // Matter epoch-s
        }

        /**
        Matter request, answered by GetYearDayScheduleResponse GetYearDaySchedule (id 0x0F)
        */
        class GetYearDayScheduleRequest {
            public const uint command_id = 0xF;
            public const string access = "invoke:admin";
            public const string conformance = "M[YDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfYearDaySchedulesSupportedPerUser")] byte YearDayIndex; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter response GetYearDayScheduleResponse (id 0x0F)
        */
        class GetYearDayScheduleResponse {
            public const uint command_id = 0xF;
            public const string conformance = "M[YDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfYearDaySchedulesSupportedPerUser")] byte YearDayIndex; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [MatterType("enum8"), FieldId(0x2), Constraint("desc")] byte Status;
            [FieldId(0x3), Conformance("O")] DateTime? LocalStartTime; // Matter epoch-s
            [FieldId(0x4), Conformance("O")] DateTime? LocalEndTime; // Matter epoch-s
        }

        /**
        Matter command (acknowledged with a status only) ClearYearDaySchedule (id 0x10)
        */
        class ClearYearDaySchedule {
            public const uint command_id = 0x10;
            public const string access = "invoke:admin";
            public const string conformance = "M[YDSCH]";
            [FieldId(0x0), Constraint("allowed 0xFE")] byte YearDayIndex;
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter command (acknowledged with a status only) SetHolidaySchedule (id 0x11)
        */
        class SetHolidaySchedule {
            public const uint command_id = 0x11;
            public const string access = "invoke:admin";
            public const string conformance = "M[HDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfHolidaySchedulesSupported")] byte HolidayIndex; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1)] DateTime LocalStartTime; // Matter epoch-s
            [FieldId(0x2)] DateTime LocalEndTime; // Matter epoch-s
            [FieldId(0x3)] OperatingModeEnum OperatingMode;
        }

        /**
        Matter request, answered by GetHolidayScheduleResponse GetHolidaySchedule (id 0x12)
        */
        class GetHolidayScheduleRequest {
            public const uint command_id = 0x12;
            public const string access = "invoke:admin";
            public const string conformance = "M[HDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfHolidaySchedulesSupported")] byte HolidayIndex; // bounds depend on another attribute, cannot be bit-packed
        }

        /**
        Matter response GetHolidayScheduleResponse (id 0x12)
        */
        class GetHolidayScheduleResponse {
            public const uint command_id = 0x12;
            public const string conformance = "M[HDSCH]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfHolidaySchedulesSupported")] byte HolidayIndex; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("enum8"), FieldId(0x1), Constraint("desc")] byte Status;
            [FieldId(0x2), Quality("nullable"), Conformance("O")] DateTime? LocalStartTime; // Matter epoch-s
            [FieldId(0x3), Quality("nullable"), Conformance("O")] DateTime? LocalEndTime; // Matter epoch-s
            [FieldId(0x4), Quality("nullable"), Conformance("O")] OperatingModeEnum? OperatingMode;
        }

        /**
        Matter command (acknowledged with a status only) ClearHolidaySchedule (id 0x13)
        */
        class ClearHolidaySchedule {
            public const uint command_id = 0x13;
            public const string access = "invoke:admin";
            public const string conformance = "M[HDSCH]";
            [FieldId(0x0), Constraint("allowed 0xFE")] byte HolidayIndex;
        }

        /**
        Matter command (acknowledged with a status only) SetUser (id 0x1A)
        */
        class SetUser {
            public const uint command_id = 0x1A;
            public const string access = "invoke:admin timed";
            public const string conformance = "M[USR]";
            [FieldId(0x0), Constraint("allowed Modify")] DataOperationTypeEnum OperationType;
            [FieldId(0x1), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [D(+10), FieldId(0x2), Quality("nullable"), Constraint("maxLength 10")] string UserName;
            [FieldId(0x3), Quality("nullable")] uint? UserUniqueID;
            [FieldId(0x4), Quality("nullable"), Constraint("allowed OccupiedDisabled")] UserStatusEnum? UserStatus;
            [FieldId(0x5), Quality("nullable"), Constraint("allowed RemoteOnlyUser")] UserTypeEnum? UserType;
            [FieldId(0x6), Quality("nullable")] CredentialRuleEnum? CredentialRule;
        }

        /**
        Matter request, answered by GetUserResponse GetUser (id 0x1B)
        */
        class GetUserRequest {
            public const uint command_id = 0x1B;
            public const string access = "invoke:admin";
            public const string conformance = "M[USR]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter response GetUserResponse (id 0x1C)
        */
        class GetUserResponse {
            public const uint command_id = 0x1C;
            public const string conformance = "M[USR]";
            [FieldId(0x0), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [D(+10), FieldId(0x1), Quality("nullable"), Constraint("maxLength 10")] string UserName;
            [FieldId(0x2), Quality("nullable")] uint? UserUniqueID;
            [FieldId(0x3), Quality("nullable")] UserStatusEnum? UserStatus;
            [FieldId(0x4), Quality("nullable")] UserTypeEnum? UserType;
            [FieldId(0x5), Quality("nullable"), Constraint("desc")] CredentialRuleEnum? CredentialRule;
            [MatterType("list<CredentialStruct>"), FieldId(0x6), Quality("nullable"), Constraint("countBetween 0..attr:NumberOfCredentialsSupportedPerUser")] CredentialStruct[,,] Credentials; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
            [MatterType("fabric-idx"), FieldId(0x7), Quality("nullable")] byte? CreatorFabricIndex;
            [MatterType("fabric-idx"), FieldId(0x8), Quality("nullable")] byte? LastModifiedFabricIndex;
            [FieldId(0x9), Quality("nullable"), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort? NextUserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter command (acknowledged with a status only) ClearUser (id 0x1D)
        */
        class ClearUser {
            public const uint command_id = 0x1D;
            public const string access = "invoke:admin timed";
            public const string conformance = "M[USR]";
            [FieldId(0x0), Constraint("allowed 0xFFFE")] ushort UserIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter request, answered by SetCredentialResponse SetCredential (id 0x22)
        */
        class SetCredentialRequest {
            public const uint command_id = 0x22;
            public const string access = "invoke:admin timed";
            public const string conformance = "M[USR]";
            [FieldId(0x0), Constraint("allowed Modify")] DataOperationTypeEnum OperationType;
            [FieldId(0x1)] CredentialStruct Credential;
            [FieldId(0x2), Constraint("desc")] Binary[,,] CredentialData;
            [FieldId(0x3), Quality("nullable"), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort? UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [FieldId(0x4), Quality("nullable"), Constraint("allowed OccupiedDisabled")] UserStatusEnum? UserStatus;
            [FieldId(0x5), Quality("nullable"), Constraint("allowed RemoteOnlyUser")] UserTypeEnum? UserType;
        }

        /**
        Matter response SetCredentialResponse (id 0x23)
        */
        class SetCredentialResponse {
            public const uint command_id = 0x23;
            public const string conformance = "M[USR]";
            [MatterType("status"), FieldId(0x0), Constraint("desc")] byte Status;
            [FieldId(0x1), Quality("nullable"), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort? UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [FieldId(0x2), Quality("nullable"), Constraint("desc"), Conformance("O")] ushort? NextCredentialIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        /**
        Matter request, answered by GetCredentialStatusResponse GetCredentialStatus (id 0x24)
        */
        class GetCredentialStatusRequest {
            public const uint command_id = 0x24;
            public const string access = "invoke:admin";
            public const string conformance = "M[USR]";
            [FieldId(0x0)] CredentialStruct Credential;
        }

        /**
        Matter response GetCredentialStatusResponse (id 0x25)
        */
        class GetCredentialStatusResponse {
            public const uint command_id = 0x25;
            public const string conformance = "M[USR]";
            [FieldId(0x0)] bool CredentialExists;
            [FieldId(0x1), Quality("nullable"), Constraint("between 1..attr:NumberOfTotalUsersSupported")] ushort? UserIndex; // bounds depend on another attribute, cannot be bit-packed; physics: counter/index, floor at 0, unbounded above -> consider [A]
            [MatterType("fabric-idx"), FieldId(0x2), Quality("nullable")] byte? CreatorFabricIndex;
            [MatterType("fabric-idx"), FieldId(0x3), Quality("nullable")] byte? LastModifiedFabricIndex;
            [FieldId(0x4), Quality("nullable"), Constraint("desc"), Conformance("O")] ushort? NextCredentialIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [FieldId(0x5), Quality("nullable"), Constraint("desc"), Conformance("O[ALIRO]")] Binary[,,] CredentialData;
        }

        /**
        Matter command (acknowledged with a status only) ClearCredential (id 0x26)
        */
        class ClearCredential {
            public const uint command_id = 0x26;
            public const string access = "invoke:admin timed";
            public const string conformance = "M[USR]";
            [FieldId(0x0), Quality("nullable"), Constraint("desc")] CredentialStruct Credential;
        }

        /**
        Matter command (acknowledged with a status only) UnboltDoor (id 0x27)
        */
        class UnboltDoor {
            public const uint command_id = 0x27;
            public const string access = "invoke:operate timed";
            public const string conformance = "M[UBOLT]";
            [FieldId(0x0), Conformance("O[(COTA&PIN)]")] Binary[,,] PINCode;
        }

        /**
        Matter command (acknowledged with a status only) SetAliroReaderConfig (id 0x28)
        */
        class SetAliroReaderConfig {
            public const uint command_id = 0x28;
            public const string access = "invoke:admin timed";
            public const string conformance = "M[ALIRO]";
            [D(32), FieldId(0x0), Constraint("allowed 32")] Binary[,,] SigningKey;
            [D(65), FieldId(0x1), Constraint("allowed 65")] Binary[,,] VerificationKey;
            [D(16), FieldId(0x2), Constraint("allowed 16")] Binary[,,] GroupIdentifier;
            [D(16), FieldId(0x3), Constraint("allowed 16"), Conformance("M[ALBU]")] Binary[,,] GroupResolvingKey;
        }

        /**
        Matter command (acknowledged with a status only) ClearAliroReaderConfig (id 0x29)
        */
        class ClearAliroReaderConfig {
            public const uint command_id = 0x29;
            public const string access = "invoke:admin timed";
            public const string conformance = "M[ALIRO]";
        }

        // ═════════════════════════ events ═════════════════════════

        /**
        Matter event DoorLockAlarm (id 0x00, priority critical)
        */
        class DoorLockAlarm {
            public const uint event_id = 0x0;
            public const string priority = "critical";
            public const string access = "read:view";
            public const string conformance = "M";
            [FieldId(0x0)] AlarmCodeEnum AlarmCode;
        }

        /**
        Matter event DoorStateChange (id 0x01, priority desc)
        */
        class DoorStateChange {
            public const uint event_id = 0x1;
            public const string priority = "desc";
            public const string access = "read:view";
            public const string conformance = "M[DPS]";
            [FieldId(0x0)] DoorStateEnum DoorState;
        }

        /**
        Matter event LockOperation (id 0x02, priority desc)
        */
        class LockOperation {
            public const uint event_id = 0x2;
            public const string priority = "desc";
            public const string access = "read:view";
            public const string conformance = "M";
            [FieldId(0x0)] LockOperationTypeEnum LockOperationType;
            [FieldId(0x1)] OperationSourceEnum OperationSource;
            [FieldId(0x2), Quality("nullable")] ushort? UserIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [MatterType("fabric-idx"), FieldId(0x3), Quality("nullable")] byte? FabricIndex;
            [MatterType("node-id"), FieldId(0x4), Quality("nullable")] ulong? SourceNode;
            [MatterType("list<CredentialStruct>"), FieldId(0x5), Quality("nullable"), Constraint("countBetween 1..attr:NumberOfCredentialsSupportedPerUser"), Conformance("O[USR]")] CredentialStruct[,,] Credentials; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
        }

        /**
        Matter event LockOperationError (id 0x03, priority desc)
        */
        class LockOperationError {
            public const uint event_id = 0x3;
            public const string priority = "desc";
            public const string access = "read:view";
            public const string conformance = "M";
            [FieldId(0x0)] LockOperationTypeEnum LockOperationType;
            [FieldId(0x1)] OperationSourceEnum OperationSource;
            [FieldId(0x2)] OperationErrorEnum OperationError;
            [FieldId(0x3), Quality("nullable")] ushort? UserIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [MatterType("fabric-idx"), FieldId(0x4), Quality("nullable")] byte? FabricIndex;
            [MatterType("node-id"), FieldId(0x5), Quality("nullable")] ulong? SourceNode;
            [MatterType("list<CredentialStruct>"), FieldId(0x6), Quality("nullable"), Constraint("countBetween 1..attr:NumberOfCredentialsSupportedPerUser"), Conformance("O[USR]")] CredentialStruct[,,] Credentials; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
        }

        /**
        Matter event LockUserChange (id 0x04, priority info)
        */
        class LockUserChange {
            public const uint event_id = 0x4;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[USR]";
            [FieldId(0x0)] LockDataTypeEnum LockDataType;
            [FieldId(0x1)] DataOperationTypeEnum DataOperationType;
            [FieldId(0x2), Constraint("allowed Remote")] OperationSourceEnum OperationSource;
            [FieldId(0x3), Quality("nullable")] ushort? UserIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
            [MatterType("fabric-idx"), FieldId(0x4), Quality("nullable")] byte? FabricIndex;
            [MatterType("node-id"), FieldId(0x5), Quality("nullable")] ulong? SourceNode;
            [FieldId(0x6), Quality("nullable")] ushort? DataIndex; // physics: counter/index, floor at 0, unbounded above -> consider [A]
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<(LockDoor, UnlockDoor, UnlockWithTimeout, SetWeekDaySchedule, ClearWeekDaySchedule, SetYearDaySchedule, ClearYearDaySchedule, SetHolidaySchedule, ClearHolidaySchedule, SetUser, ClearUser, ClearCredential, UnboltDoor, SetAliroReaderConfig, ClearAliroReaderConfig)>]
            struct Invoke { }

            // commands with a data response: request/response calls initiated by the client
            (L____________, GetWeekDayScheduleResponse) GetWeekDaySchedule(GetWeekDayScheduleRequest req);
            (L____________, GetYearDayScheduleResponse) GetYearDaySchedule(GetYearDayScheduleRequest req);
            (L____________, GetHolidayScheduleResponse) GetHolidaySchedule(GetHolidayScheduleRequest req);
            (L____________, GetUserResponse) GetUser(GetUserRequest req);
            (L____________, SetCredentialResponse) SetCredential(SetCredentialRequest req);
            (L____________, GetCredentialStatusResponse) GetCredentialStatus(GetCredentialStatusRequest req);

            // events (and unreferenced responses) are reported by the server
            [____________r<(DoorLockAlarm, DoorStateChange, LockOperation, LockOperationError, LockUserChange)>]
            struct Report { }

            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
