// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: FanControl.xml + globals
// Matter cluster Fan Control Cluster id 0x0202 revision 7
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'Step'/>
    */
    public interface FanControl {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Fan Control Cluster" (id 0x0202, revision 7).
        rev 1: Mandatory global ClusterRevision attribute added
        rev 2: New data model format and notation; Percent, speed and motion settings; General cleanup
        rev 3: Addition of AirflowDirection and Step command
        rev 4: Change conformance for FanModeSequenceEnum
        rev 5: Clarified attribute usage, added conformance column
        rev 6: Removed Zigbee related elements, removed P quality
        rev 7: Added Q quality for PercentCurrent and SpeedCurrent
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x202;
            public const string cluster_name = "Fan Control Cluster";
            public const uint revision = 7;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            0-SpeedMax Fan Speeds (code SPD)
            */
            MultiSpeed = 1,
            /**
            Automatic mode supported for fan speed (code AUT)
            */
            Auto = 2,
            /**
            Rocking movement supported (code RCK)
            */
            Rocking = 4,
            /**
            Wind emulation supported (code WND)
            */
            Wind = 8,
            /**
            Step command supported (code STEP)
            */
            Step = 16,
            /**
            Airflow Direction attribute is supported (code DIR)
            */
            AirflowDirection = 32,
        }

        /**
        Matter enum AirflowDirectionEnum
        */
        enum AirflowDirectionEnum {
            /**
            Airflow is in the forward direction
            */
            Forward = 0,
            /**
            Airflow is in the reverse direction
            */
            Reverse = 1,
        }

        /**
        Matter enum FanModeEnum
        */
        enum FanModeEnum {
            /**
            Fan is off
            */
            Off = 0,
            /**
            Fan using low speed
            */
            Low = 1,
            /**
            Fan using medium speed
            */
            Medium = 2,
            /**
            Fan using high speed
            */
            High = 3,
            On = 4,
            /**
            Fan is using auto mode
            */
            Auto = 5,
            /**
            Fan is using smart mode
            */
            Smart = 6,
        }

        /**
        Matter enum FanModeSequenceEnum
        */
        enum FanModeSequenceEnum {
            /**
            Fan is capable of off, low, medium and high modes
            */
            OffLowMedHigh = 0,
            /**
            Fan is capable of off, low and high modes
            */
            OffLowHigh = 1,
            /**
            Fan is capable of off, low, medium, high and auto modes
            */
            OffLowMedHighAuto = 2,
            /**
            Fan is capable of off, low, high and auto modes
            */
            OffLowHighAuto = 3,
            /**
            Fan is capable of off, high and auto modes
            */
            OffHighAuto = 4,
            /**
            Fan is capable of off and high modes
            */
            OffHigh = 5,
        }

        /**
        Matter enum StepDirectionEnum
        */
        enum StepDirectionEnum {
            /**
            Step moves in increasing direction
            */
            Increase = 0,
            /**
            Step moves in decreasing direction
            */
            Decrease = 1,
        }

        /**
        Matter bitmap RockBitmap (map8)
        */
        [Flags]
        enum RockBitmap {
            /**
            Indicate rock left to right
            */
            RockLeftRight = 1,
            /**
            Indicate rock up and down
            */
            RockUpDown = 2,
            /**
            Indicate rock around
            */
            RockRound = 4,
        }

        /**
        Matter bitmap WindBitmap (map8)
        */
        [Flags]
        enum WindBitmap {
            /**
            Indicate sleep wind
            */
            SleepWind = 1,
            /**
            Indicate natural wind
            */
            NaturalWind = 2,
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [AttrId(0x0), Access("read:view write:operate"), Quality("nonVolatile"), Constraint("desc")] FanModeEnum FanMode;
            [AttrId(0x1), Access("read:view"), Quality("fixed")] FanModeSequenceEnum FanModeSequence;
            [MatterType("percent"), MinMax(0, 100), AttrId(0x2), Access("read:view write:operate"), Quality("nullable"), Constraint("max 100")] byte? PercentSetting;
            [MatterType("percent"), MinMax(0, 100), AttrId(0x3), Access("read:view"), Quality("quieterReporting"), Constraint("max 100")] byte PercentCurrent;
            [MinMax(1, 100), AttrId(0x4), Access("read:view"), Quality("fixed"), Constraint("between 1..100"), Conformance("M[SPD]")] byte? SpeedMax;
            [AttrId(0x5), Access("read:view write:operate"), Quality("nullable"), Constraint("max attr:SpeedMax"), Conformance("M[SPD]")] byte? SpeedSetting; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x6), Access("read:view"), Quality("quieterReporting"), Constraint("max attr:SpeedMax"), Conformance("M[SPD]")] byte? SpeedCurrent; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x7), Access("read:view"), Quality("fixed"), Constraint("min 1"), Conformance("M[RCK]")] RockBitmap? RockSupport;
            [AttrId(0x8), Access("read:view write:operate"), Constraint("desc"), Conformance("M[RCK]")] RockBitmap? RockSetting;
            [AttrId(0x9), Access("read:view"), Quality("fixed"), Constraint("min 1"), Conformance("M[WND]")] WindBitmap? WindSupport;
            [AttrId(0xA), Access("read:view write:operate"), Constraint("desc"), Conformance("M[WND]")] WindBitmap? WindSetting;
            [AttrId(0xB), Access("read:view write:operate"), Conformance("M[DIR]")] AirflowDirectionEnum? AirflowDirection;
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) Step (id 0x00)
        */
        class Step {
            public const uint command_id = 0x0;
            public const string access = "invoke:operate";
            public const string conformance = "M[STEP]";
            [FieldId(0x0)] StepDirectionEnum Direction;
            [FieldId(0x1), Conformance("O")] bool? Wrap;
            [FieldId(0x2), Conformance("O")] bool? LowestOff;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<Step>]
            struct Invoke { }


            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
