// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: Identify.xml + globals
// Matter cluster Identify Cluster id 0x0003 revision 6
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'IdentifyCommand'/>
        <see cref = 'TriggerEffect'/>
    */
    public interface Identify {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Identify Cluster" (id 0x0003, revision 6).
        rev 1: Mandatory global ClusterRevision attribute added
        rev 2: CCB 2808
        rev 3: All Hubs changes
        rev 4: New data model format and notation; add IdentifyType
        rev 5: Removed Query feature
        rev 6: Added Q quality for IdentifyTime attribute
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x3;
            public const string cluster_name = "Identify Cluster";
            public const uint revision = 6;
        }

        /**
        Matter enum EffectIdentifierEnum
        */
        enum EffectIdentifierEnum {
            /**
            e.g., Light is turned on/off once.
            */
            Blink = 0x00,
            /**
            e.g., Light is turned on/off over 1 second and repeated 15 times.
            */
            Breathe = 0x01,
            /**
            e.g., Colored light turns green for 1 second; non-colored light flashes twice.
            */
            Okay = 0x02,
            /**
            e.g., Colored light turns orange for 8 seconds; non-colored light switches to the maximum brightness for 0.5s
            and then minimum brightness for 7.5s.
            */
            ChannelChange = 0x0B,
            /**
            Complete the current effect sequence before terminating. e.g., if in the middle of a breathe effect (as
            above), first complete the current 1s breathe effect and then terminate the effect.
            */
            FinishEffect = 0xFE,
            /**
            Terminate the effect as soon as possible.
            */
            StopEffect = 0xFF,
        }

        // enum with fewer than two items: AdHoc rejects such enums, kept as a constants container
        public struct EffectVariantEnum {
            /**
            Indicates the default effect is used
            */
            public const int Default = 0x00;
        }

        /**
        Matter enum IdentifyTypeEnum
        */
        enum IdentifyTypeEnum {
            /**
            No presentation.
            */
            None = 0x00,
            /**
            Light output of a lighting product.
            */
            LightOutput = 0x01,
            /**
            Typically a small LED.
            */
            VisibleIndicator = 0x02,
            AudibleBeep = 0x03,
            /**
            Presentation will be visible on display screen.
            */
            Display = 0x04,
            /**
            Presentation will be conveyed by actuator functionality such as through a window blind operation or in-wall
            relay.
            */
            Actuator = 0x05,
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [AttrId(0x0), Access("read:view write:operate"), Quality("quieterReporting")] ushort IdentifyTime;
            [AttrId(0x1), Access("read:view"), Constraint("desc")] IdentifyTypeEnum IdentifyType;
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) Identify (id 0x00)
        */
        class IdentifyCommand {
            public const uint command_id = 0x0;
            public const string access = "invoke:manage";
            public const string conformance = "M";
            [FieldId(0x0)] ushort IdentifyTime;
        }

        /**
        Matter command (acknowledged with a status only) TriggerEffect (id 0x40)
        */
        class TriggerEffect {
            public const uint command_id = 0x40;
            public const string access = "invoke:manage";
            public const string conformance = "O";
            [FieldId(0x0), Constraint("desc")] EffectIdentifierEnum EffectIdentifier;
            [MatterType("EffectVariantEnum"), FieldId(0x1), Constraint("desc")] byte EffectVariant; // values: constants container EffectVariantEnum
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<(IdentifyCommand, TriggerEffect)>]
            struct Invoke { }


            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
