// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: LevelControl.xml + globals
// Matter cluster Level Control Cluster id 0x0008 revision 8
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'Move'/>
        <see cref = 'MoveToClosestFrequency'/>
        <see cref = 'MoveToLevel'/>
        <see cref = 'MoveToLevelWithOnOff'/>
        <see cref = 'MoveWithOnOff'/>
        <see cref = 'Step'/>
        <see cref = 'StepWithOnOff'/>
        <see cref = 'Stop'/>
        <see cref = 'StopWithOnOff'/>
    */
    public interface LevelControl {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Level Control Cluster" (id 0x0008, revision 8).
        rev 1: Mandatory global ClusterRevision attribute added
        rev 2: Added Options attribute, state change table; ZLO 1.0; Base cluster (no change) CCB 2085 1775 2281 2147
        rev 3: CCB 2574 2616 2659 2702 2814 2818 2819 2898
        rev 4: FeatureMap support with On/Off, Lighting and Frequency features
        rev 5: New data model format and notation
        rev 6: Added Q quality for CurrentLevel, CurrentFrequency and RemainingTime attributes, added clarifications
        for behavior related to Step value and adjusted constraint of DefaultMoveRate
        rev 7: Simplify constraint, added F quality, changed the conformance to mandatory for MinLevel and MaxLevel,
        and removed P quality
        rev 8: Mark provisional Frequency feature and associated elements as obsolete
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x8;
            public const string cluster_name = "Level Control Cluster";
            public const uint revision = 8;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            Dependency with the On/Off cluster (code OO)
            */
            OnOff = 1,
            /**
            Behavior that supports lighting applications (code LT)
            */
            Lighting = 2,
            /**
            Supports frequency attributes and behavior. (code FQ)
            */
            Frequency = 4,
        }

        /**
        Matter enum MoveModeEnum
        */
        enum MoveModeEnum {
            /**
            Increase the level
            */
            Up = 0,
            /**
            Decrease the level
            */
            Down = 1,
        }

        /**
        Matter enum StepModeEnum
        */
        enum StepModeEnum {
            /**
            Step upwards
            */
            Up = 0,
            /**
            Step downwards
            */
            Down = 1,
        }

        /**
        Matter bitmap OptionsBitmap (map8)
        */
        [Flags]
        enum OptionsBitmap {
            /**
            Dependency on On/Off cluster
            */
            ExecuteIfOff = 1,
            /**
            Dependency on Color Control cluster
            */
            CoupleColorTempToLevel = 2,
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [AttrId(0x0), Access("read:view"), Quality("nullable nonVolatile scene quieterReporting"), Constraint("between attr:MinLevel..attr:MaxLevel")] byte? CurrentLevel; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x1), Access("read:view"), Quality("quieterReporting"), Conformance("M[LT]")] ushort? RemainingTime;
            [MinMax(0, 254), AttrId(0x2), Access("read:view"), Quality("fixed"), Default("1"), Constraint("max 254"), Conformance("otherwise(M[(revision>=revision)]; O)")] byte? MinLevel;
            [AttrId(0x3), Access("read:view"), Quality("fixed"), Default("254"), Constraint("between attr:MinLevel..254"), Conformance("otherwise(M[(revision>=revision)]; O)")] byte? MaxLevel; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x4), Access("read:view"), Quality("scene quieterReporting"), Constraint("between attr:MinFrequency..attr:MaxFrequency"), Conformance("M[FQ]")] ushort? CurrentFrequency; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x5), Access("read:view"), Conformance("M[FQ]")] ushort? MinFrequency;
            [AttrId(0x6), Access("read:view"), Constraint("min attr:MinFrequency"), Conformance("M[FQ]")] ushort? MaxFrequency; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0xF), Access("read:view write:operate"), Constraint("desc")] OptionsBitmap Options;
            [AttrId(0x10), Access("read:view write:operate"), Default("0"), Conformance("O")] ushort? OnOffTransitionTime;
            [AttrId(0x11), Access("read:view write:operate"), Quality("nullable"), Constraint("between attr:MinLevel..attr:MaxLevel")] byte? OnLevel; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x12), Access("read:view write:operate"), Quality("nullable"), Default("null"), Conformance("O")] ushort? OnTransitionTime;
            [AttrId(0x13), Access("read:view write:operate"), Quality("nullable"), Default("null"), Conformance("O")] ushort? OffTransitionTime;
            [MinMax(1, 255), AttrId(0x14), Access("read:view write:operate"), Quality("nullable"), Default("MS"), Constraint("min 1"), Conformance("O")] byte? DefaultMoveRate;
            [AttrId(0x4000), Access("read:view write:manage"), Quality("nullable nonVolatile"), Constraint("desc"), Conformance("M[LT]")] byte? StartUpCurrentLevel;
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) MoveToLevel (id 0x00)
        */
        class MoveToLevel {
            public const uint command_id = 0x0;
            public const string access = "invoke:operate";
            public const string conformance = "M";
            [MinMax(0, 254), FieldId(0x0), Constraint("max 254")] byte Level;
            [FieldId(0x1), Quality("nullable")] ushort? TransitionTime;
            [FieldId(0x2), Constraint("desc")] OptionsBitmap OptionsMask;
            [FieldId(0x3), Constraint("desc")] OptionsBitmap OptionsOverride;
        }

        /**
        Matter command (acknowledged with a status only) Move (id 0x01)
        */
        class Move {
            public const uint command_id = 0x1;
            public const string access = "invoke:operate";
            public const string conformance = "M";
            [FieldId(0x0), Constraint("desc")] MoveModeEnum MoveMode;
            [FieldId(0x1), Quality("nullable")] byte? Rate;
            [FieldId(0x2), Constraint("desc")] OptionsBitmap OptionsMask;
            [FieldId(0x3), Constraint("desc")] OptionsBitmap OptionsOverride;
        }

        /**
        Matter command (acknowledged with a status only) Step (id 0x02)
        */
        class Step {
            public const uint command_id = 0x2;
            public const string access = "invoke:operate";
            public const string conformance = "M";
            [FieldId(0x0), Constraint("desc")] StepModeEnum StepMode;
            [FieldId(0x1)] byte StepSize;
            [FieldId(0x2), Quality("nullable")] ushort? TransitionTime;
            [FieldId(0x3), Constraint("desc")] OptionsBitmap OptionsMask;
            [FieldId(0x4), Constraint("desc")] OptionsBitmap OptionsOverride;
        }

        /**
        Matter command (acknowledged with a status only) Stop (id 0x03)
        */
        class Stop {
            public const uint command_id = 0x3;
            public const string access = "invoke:operate";
            public const string conformance = "M";
            [FieldId(0x0), Constraint("desc")] OptionsBitmap OptionsMask;
            [FieldId(0x1), Constraint("desc")] OptionsBitmap OptionsOverride;
        }

        /**
        Matter command (acknowledged with a status only) MoveToLevelWithOnOff (id 0x04)
        */
        class MoveToLevelWithOnOff {
            public const uint command_id = 0x4;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) MoveWithOnOff (id 0x05)
        */
        class MoveWithOnOff {
            public const uint command_id = 0x5;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) StepWithOnOff (id 0x06)
        */
        class StepWithOnOff {
            public const uint command_id = 0x6;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) StopWithOnOff (id 0x07)
        */
        class StopWithOnOff {
            public const uint command_id = 0x7;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) MoveToClosestFrequency (id 0x08)
        */
        class MoveToClosestFrequency {
            public const uint command_id = 0x8;
            public const string access = "invoke:operate";
            public const string conformance = "M[FQ]";
            [FieldId(0x0)] ushort Frequency;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<(MoveToLevel, Move, Step, Stop, MoveToLevelWithOnOff, MoveWithOnOff, StepWithOnOff, StopWithOnOff, MoveToClosestFrequency)>]
            struct Invoke { }


            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
