// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: OnOff.xml + globals
// Matter cluster On/Off Cluster id 0x0006 revision 7
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'Off'/>
        <see cref = 'OffWithEffect'/>
        <see cref = 'On'/>
        <see cref = 'OnWithRecallGlobalScene'/>
        <see cref = 'OnWithTimedOff'/>
        <see cref = 'Toggle'/>
    */
    public interface OnOff {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "On/Off Cluster" (id 0x0006, revision 7).
        rev 1: Mandatory global ClusterRevision attribute added; CCB 1555
        rev 2: ZLO 1.0: StartUpOnOff
        rev 3: FeatureMap global attribute support with Level Control and Lighting feature
        rev 4: New data model format and notation
        rev 5: Addition of Dead Front behavior and associated FeatureMap entry
        rev 6: Addition of OffOnly feature and associated FeatureMap entry
        rev 7: Added Q quality to OnTime and OffWaitTime attributes
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x6;
            public const string cluster_name = "On/Off Cluster";
            public const uint revision = 7;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            Behavior that supports lighting applications (code LT)
            */
            Lighting = 1,
            /**
            Device has Dead Front behavior (code DF)
            */
            DeadFrontBehavior = 2,
            /**
            Device supports the OffOnly Feature feature (code OFFONLY)
            */
            OffOnly = 4,
        }

        /**
        Matter enum DelayedAllOffEffectVariantEnum
        */
        enum DelayedAllOffEffectVariantEnum {
            /**
            Fade to off in 0.8 seconds
            */
            DelayedOffFastFade = 0x00,
            /**
            No fade
            */
            NoFade = 0x01,
            /**
            50% dim down in 0.8 seconds then fade to off in 12 seconds
            */
            DelayedOffSlowFade = 0x02,
        }

        // enum with fewer than two items: AdHoc rejects such enums, kept as a constants container
        public struct DyingLightEffectVariantEnum {
            /**
            20% dim up in 0.5s then fade to off in 1 second
            */
            public const int DyingLightFadeOff = 0x00;
        }

        /**
        Matter enum EffectIdentifierEnum
        */
        enum EffectIdentifierEnum {
            /**
            Delayed All Off
            */
            DelayedAllOff = 0x00,
            /**
            Dying Light
            */
            DyingLight = 0x01,
        }

        /**
        Matter enum StartUpOnOffEnum
        */
        enum StartUpOnOffEnum {
            /**
            Set the OnOff attribute to FALSE
            */
            Off = 0,
            /**
            Set the OnOff attribute to TRUE
            */
            On = 1,
            /**
            If the previous value of the OnOff attribute is equal to FALSE, set the OnOff attribute to TRUE. If the
            previous value of the OnOff attribute is equal to TRUE, set the OnOff attribute to FALSE (toggle).
            */
            Toggle = 2,
        }

        // bitmap with a single field: AdHoc rejects one-member enums, kept as a constants container
        public struct OnOffControlBitmap {
            /**
            Indicates a command is only accepted when in On state.
            */
            public const ulong AcceptOnlyWhenOn = 1;
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [AttrId(0x0), Access("read:view"), Quality("nonVolatile scene")] bool OnOff;
            [AttrId(0x4000), Access("read:view"), Conformance("M[LT]")] bool? GlobalSceneControl;
            [AttrId(0x4001), Access("read:view write:operate"), Quality("quieterReporting"), Conformance("M[LT]")] ushort? OnTime;
            [AttrId(0x4002), Access("read:view write:operate"), Quality("quieterReporting"), Conformance("M[LT]")] ushort? OffWaitTime;
            [AttrId(0x4003), Access("read:view write:manage"), Quality("nullable nonVolatile"), Constraint("desc"), Conformance("M[LT]")] StartUpOnOffEnum? StartUpOnOff;
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) Off (id 0x00)
        */
        class Off {
            public const uint command_id = 0x0;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) On (id 0x01)
        */
        class On {
            public const uint command_id = 0x1;
            public const string access = "invoke:operate";
            public const string conformance = "M[!OFFONLY]";
        }

        /**
        Matter command (acknowledged with a status only) Toggle (id 0x02)
        */
        class Toggle {
            public const uint command_id = 0x2;
            public const string access = "invoke:operate";
            public const string conformance = "M[!OFFONLY]";
        }

        /**
        Matter command (acknowledged with a status only) OffWithEffect (id 0x40)
        */
        class OffWithEffect {
            public const uint command_id = 0x40;
            public const string access = "invoke:operate";
            public const string conformance = "M[LT]";
            [FieldId(0x0), Constraint("desc")] EffectIdentifierEnum EffectIdentifier;
            [MatterType("enum8"), FieldId(0x1), Constraint("desc")] byte EffectVariant;
        }

        /**
        Matter command (acknowledged with a status only) OnWithRecallGlobalScene (id 0x41)
        */
        class OnWithRecallGlobalScene {
            public const uint command_id = 0x41;
            public const string access = "invoke:operate";
            public const string conformance = "M[LT]";
        }

        /**
        Matter command (acknowledged with a status only) OnWithTimedOff (id 0x42)
        */
        class OnWithTimedOff {
            public const uint command_id = 0x42;
            public const string access = "invoke:operate";
            public const string conformance = "M[LT]";
            [MatterType("OnOffControlBitmap"), MinMax(0, 1), FieldId(0x0), Constraint("between 0..1")] byte OnOffControl; // values: constants container OnOffControlBitmap
            [MinMax(0, 65534), FieldId(0x1), Constraint("max 0xFFFE")] ushort OnTime;
            [MinMax(0, 65534), FieldId(0x2), Constraint("max 0xFFFE")] ushort OffWaitTime;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<(Off, On, Toggle, OffWithEffect, OnWithRecallGlobalScene, OnWithTimedOff)>]
            struct Invoke { }


            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
