// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: Switch.xml + globals
// Matter cluster Switch Cluster id 0x003B revision 2
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'InitialPress'/>
        <see cref = 'LongPress'/>
        <see cref = 'LongRelease'/>
        <see cref = 'MultiPressComplete'/>
        <see cref = 'MultiPressOngoing'/>
        <see cref = 'ShortRelease'/>
        <see cref = 'SwitchLatched'/>
    */
    public interface Switch {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Switch Cluster" (id 0x003B, revision 2).
        rev 1: Initial revision
        rev 2: Behavior clarifications for ambiguous combinations of events; Introduction of
        TotalNumberOfPressesCounted == 0 when MultiPressMax is exceeded; Introduction of ActionSwitch feature flag.
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x3B;
            public const string cluster_name = "Switch Cluster";
            public const uint revision = 2;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            Switch is latching (code LS)
            */
            LatchingSwitch = 1,
            /**
            Switch is momentary (code MS)
            */
            MomentarySwitch = 2,
            /**
            Switch supports release events generation (code MSR)
            */
            MomentarySwitchRelease = 4,
            /**
            Switch supports long press detection (code MSL)
            */
            MomentarySwitchLongPress = 8,
            /**
            Switch supports multi-press detection (code MSM)
            */
            MomentarySwitchMultiPress = 16,
            /**
            Switch is momentary, targeted at specific user actions (focus on multi-press and optionally long press) with a
            reduced event generation scheme (code AS)
            */
            ActionSwitch = 32,
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [MinMax(2, 255), AttrId(0x0), Access("read:view"), Quality("fixed"), Constraint("min 2")] byte NumberOfPositions;
            [AttrId(0x1), Access("read:view"), Quality("nonVolatile"), Constraint("max (attr:NumberOfPositions subtract 1)")] byte CurrentPosition; // bounds depend on another attribute, cannot be bit-packed
            [MinMax(2, 255), AttrId(0x2), Access("read:view"), Quality("fixed"), Constraint("min 2"), Conformance("M[MSM]")] byte? MultiPressMax;
        }

        // ═════════════════════════ events ═════════════════════════

        /**
        Matter event SwitchLatched (id 0x00, priority info)
        */
        class SwitchLatched {
            public const uint event_id = 0x0;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[LS]";
            [FieldId(0x0), Constraint("between 0..(attr:NumberOfPositions subtract 1)")] byte NewPosition; // bounds depend on another attribute, cannot be bit-packed
        }

        /**
        Matter event InitialPress (id 0x01, priority info)
        */
        class InitialPress {
            public const uint event_id = 0x1;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[MS]";
            [FieldId(0x0), Constraint("between 0..(attr:NumberOfPositions subtract 1)")] byte NewPosition; // bounds depend on another attribute, cannot be bit-packed
        }

        /**
        Matter event LongPress (id 0x02, priority info)
        */
        class LongPress {
            public const uint event_id = 0x2;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[MSL]";
            [FieldId(0x0), Constraint("between 0..(attr:NumberOfPositions subtract 1)")] byte NewPosition; // bounds depend on another attribute, cannot be bit-packed
        }

        /**
        Matter event ShortRelease (id 0x03, priority info)
        */
        class ShortRelease {
            public const uint event_id = 0x3;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[MSR]";
            [FieldId(0x0), Constraint("between 0..(attr:NumberOfPositions subtract 1)")] byte PreviousPosition; // bounds depend on another attribute, cannot be bit-packed
        }

        /**
        Matter event LongRelease (id 0x04, priority info)
        */
        class LongRelease {
            public const uint event_id = 0x4;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[MSL]";
            [FieldId(0x0), Constraint("between 0..(attr:NumberOfPositions subtract 1)")] byte PreviousPosition; // bounds depend on another attribute, cannot be bit-packed
        }

        /**
        Matter event MultiPressOngoing (id 0x05, priority info)
        */
        class MultiPressOngoing {
            public const uint event_id = 0x5;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[(MSM&!AS)]";
            [FieldId(0x0), Constraint("between 0..(attr:NumberOfPositions subtract 1)")] byte NewPosition; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("between 2..attr:MultiPressMax")] byte CurrentNumberOfPressesCounted; // bounds depend on another attribute, cannot be bit-packed
        }

        /**
        Matter event MultiPressComplete (id 0x06, priority info)
        */
        class MultiPressComplete {
            public const uint event_id = 0x6;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "M[MSM]";
            [FieldId(0x0), Constraint("between 0..(attr:NumberOfPositions subtract 1)")] byte PreviousPosition; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x1), Constraint("max attr:MultiPressMax")] byte TotalNumberOfPressesCounted; // bounds depend on another attribute, cannot be bit-packed
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {

            // events (and unreferenced responses) are reported by the server
            [____________r<(SwitchLatched, InitialPress, LongPress, ShortRelease, LongRelease, MultiPressOngoing, MultiPressComplete)>]
            struct Report { }

            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
