// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: TemperatureMeasurement.xml + globals
// Matter cluster Temperature Measurement Cluster id 0x0402 revision 6
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
    */
    public interface TemperatureMeasurement {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Temperature Measurement Cluster" (id 0x0402, revision 6).
        rev 1: Mandatory global ClusterRevision attribute added
        rev 2: CCB 2241 2370
        rev 3: CCB 2823
        rev 4: New data model format and notation
        rev 5: Removed P quality
        rev 6: Added F quality to MinMeasuredValue, MaxMeasuredValue and Tolerance attributes
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x402;
            public const string cluster_name = "Temperature Measurement Cluster";
            public const uint revision = 6;
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [MatterType("temperature"), AttrId(0x0), Access("read:view"), Quality("nullable"), Constraint("between attr:MinMeasuredValue..attr:MaxMeasuredValue")] short? MeasuredValue; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("temperature"), MinMax(-27315, 32766), AttrId(0x1), Access("read:view"), Quality("nullable fixed"), Constraint("between -27315..32766")] short? MinMeasuredValue;
            [MatterType("temperature"), AttrId(0x2), Access("read:view"), Quality("nullable fixed"), Constraint("min (attr:MinMeasuredValue add 1)")] short? MaxMeasuredValue; // bounds depend on another attribute, cannot be bit-packed
            [MinMax(0, 2048), AttrId(0x3), Access("read:view"), Quality("fixed"), Default("0"), Constraint("max 2048"), Conformance("O")] ushort? Tolerance;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {

            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
