// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: Thermostat.xml + globals
// Matter cluster Thermostat Cluster id 0x0201 revision 12
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'ActivePresetChange'/>
        <see cref = 'ActiveScheduleChange'/>
        <see cref = 'AddThermostatSuggestionRequest'/>
        <see cref = 'AddThermostatSuggestionResponse'/>
        <see cref = 'Attributes'/>
        <see cref = 'ClearWeeklySchedule'/>
        <see cref = 'GetWeeklyScheduleRequest'/>
        <see cref = 'GetWeeklyScheduleResponse'/>
        <see cref = 'LocalTemperatureChange'/>
        <see cref = 'OccupancyChange'/>
        <see cref = 'PresetStruct'/>
        <see cref = 'PresetTypeStruct'/>
        <see cref = 'RemoveThermostatSuggestion'/>
        <see cref = 'RunningModeChange'/>
        <see cref = 'RunningStateChange'/>
        <see cref = 'ScheduleStruct'/>
        <see cref = 'ScheduleTransitionStruct'/>
        <see cref = 'ScheduleTypeStruct'/>
        <see cref = 'SensorScheduleTransitionStruct'/>
        <see cref = 'SetActivePresetRequest'/>
        <see cref = 'SetActiveScheduleRequest'/>
        <see cref = 'SetWeeklySchedule'/>
        <see cref = 'SetpointChange'/>
        <see cref = 'SetpointRaiseLower'/>
        <see cref = 'SystemModeChange'/>
        <see cref = 'ThermostatSensorStruct'/>
        <see cref = 'ThermostatSuggestionStruct'/>
        <see cref = 'WeeklyScheduleTransitionStruct'/>
        <see cref = 'octstr_max_16'/>
    */
    public interface Thermostat {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Thermostat Cluster" (id 0x0201, revision 12).
        rev 1: Mandatory global ClusterRevision attribute added; fixed some defaults; CCB 1823, 1480
        rev 2: CCB 1981 2186 2249 2250 2251; NFR Thermostat Setback
        rev 3: CCB 2477 2560 2773 2777 2815 2816 3029
        rev 4: All Hubs changes
        rev 5: New data model format and notation, added FeatureMap, collapsed attribute sets, clarified edge cases
        around limits, default value of xxxSetpointLimit now respects AbsxxxSetpointLimit
        rev 6: Introduced the LTNE feature and adapted text (spec issue #5778)
        rev 7: Update constraints on local temperature calibration and minimum setpoint deadband and introduced
        Presets and MatterScheduleConfiguration features
        rev 8: Added comment regarding writing to ControlSequenceOfOperation
        rev 9: Removed AlarmMask attribute and AlarmCodeBitmap Type
        rev 10: Removed Zigbee related elements and P quality, deprecated ThermostatProgrammingOperationMode and
        removed ProgrammingOperationModeBitmap. and deprecated Setback feature and related elements.
        rev 11: Added support for Thermostat suggestions. Added events.
        rev 12: Mandate minimum value of 1 for TemperatureSetpointHoldDuration. Added Critical Protection attributes.
        Added support for scheduling sensors.
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x201;
            public const string cluster_name = "Thermostat Cluster";
            public const uint revision = 12;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            Thermostat is capable of managing a heating device (code HEAT)
            */
            Heating = 1,
            /**
            Thermostat is capable of managing a cooling device (code COOL)
            */
            Cooling = 2,
            /**
            Supports Occupied and Unoccupied setpoints (code OCC)
            */
            Occupancy = 4,
            /**
            (code SCH)
            */
            ScheduleConfiguration = 8,
            /**
            (code SB)
            */
            Setback = 16,
            /**
            Supports a System Mode of Auto (code AUTO)
            */
            AutoMode = 32,
            /**
            Thermostat does not expose the LocalTemperature Value in the LocalTemperature attribute (code LTNE)
            */
            LocalTemperatureNotExposed = 64,
            /**
            Supports enhanced schedules (code MSCH)
            */
            MatterScheduleConfiguration = 128,
            /**
            Thermostat supports setpoint presets (code PRES)
            */
            Presets = 256,
            /**
            Thermostat supports events (code TEVT)
            */
            Events = 512,
            /**
            Thermostat supports suggestions (code TSUGGEST)
            */
            ThermostatSuggestions = 1024,
            /**
            Thermostat supports scheduling sensors (code SENSORS)
            */
            ThermostatSensors = 2048,
        }

        // enum with fewer than two items: AdHoc rejects such enums, kept as a constants container
        public struct ACCapacityFormatEnum {
            /**
            British Thermal Unit per Hour
            */
            public const int BTUh = 0;
        }

        /**
        Matter enum ACCompressorTypeEnum
        */
        enum ACCompressorTypeEnum {
            /**
            Unknown compressor type
            */
            Unknown = 0,
            /**
            Max working ambient 43 °C
            */
            T1 = 1,
            /**
            Max working ambient 35 °C
            */
            T2 = 2,
            /**
            Max working ambient 52 °C
            */
            T3 = 3,
        }

        /**
        Matter enum ACLouverPositionEnum
        */
        enum ACLouverPositionEnum {
            /**
            Fully Closed
            */
            Closed = 1,
            /**
            Fully Open
            */
            Open = 2,
            /**
            Quarter Open
            */
            Quarter = 3,
            /**
            Half Open
            */
            Half = 4,
            /**
            Three Quarters Open
            */
            ThreeQuarters = 5,
        }

        /**
        Matter enum ACRefrigerantTypeEnum
        */
        enum ACRefrigerantTypeEnum {
            /**
            Unknown Refrigerant Type
            */
            Unknown = 0,
            /**
            R22 Refrigerant
            */
            R22 = 1,
            /**
            R410a Refrigerant
            */
            R410a = 2,
            /**
            R407c Refrigerant
            */
            R407c = 3,
        }

        /**
        Matter enum ACTypeEnum
        */
        enum ACTypeEnum {
            /**
            Unknown AC Type
            */
            Unknown = 0,
            /**
            Cooling and Fixed Speed
            */
            CoolingFixed = 1,
            /**
            Heat Pump and Fixed Speed
            */
            HeatPumpFixed = 2,
            /**
            Cooling and Inverter
            */
            CoolingInverter = 3,
            /**
            Heat Pump and Inverter
            */
            HeatPumpInverter = 4,
        }

        /**
        Matter enum ControlSequenceOfOperationEnum
        */
        enum ControlSequenceOfOperationEnum {
            /**
            Heat and Emergency are not possible
            */
            CoolingOnly = 0,
            /**
            Heat and Emergency are not possible
            */
            CoolingWithReheat = 1,
            /**
            Cool and precooling (see Terms) are not possible
            */
            HeatingOnly = 2,
            /**
            Cool and precooling are not possible
            */
            HeatingWithReheat = 3,
            /**
            All modes are possible
            */
            CoolingAndHeating = 4,
            /**
            All modes are possible
            */
            CoolingAndHeatingWithReheat = 5,
        }

        /**
        Matter enum PresetScenarioEnum
        */
        enum PresetScenarioEnum {
            /**
            The thermostat-controlled area is occupied
            */
            Occupied = 1,
            /**
            The thermostat-controlled area is unoccupied
            */
            Unoccupied = 2,
            /**
            Users are likely to be sleeping
            */
            Sleep = 3,
            /**
            Users are likely to be waking up
            */
            Wake = 4,
            /**
            Users are on vacation
            */
            Vacation = 5,
            /**
            Users are likely to be going to sleep
            */
            GoingToSleep = 6,
            /**
            Custom presets
            */
            UserDefined = 254,
        }

        /**
        Matter enum SetpointChangeSourceEnum
        */
        enum SetpointChangeSourceEnum {
            /**
            Manual, user-initiated setpoint change via the thermostat
            */
            Manual = 0,
            /**
            Schedule/internal programming-initiated setpoint change
            */
            Schedule = 1,
            /**
            Externally-initiated setpoint change (e.g., DRLC cluster command, attribute write)
            */
            External = 2,
        }

        /**
        Matter enum SetpointRaiseLowerModeEnum
        */
        enum SetpointRaiseLowerModeEnum {
            /**
            Adjust Heat Setpoint
            */
            Heat = 0,
            /**
            Adjust Cool Setpoint
            */
            Cool = 1,
            /**
            Adjust Heat Setpoint and Cool Setpoint
            */
            Both = 2,
        }

        /**
        Matter enum StartOfWeekEnum
        */
        enum StartOfWeekEnum {
            Sunday = 0,
            Monday = 1,
            Tuesday = 2,
            Wednesday = 3,
            Thursday = 4,
            Friday = 5,
            Saturday = 6,
        }

        /**
        Matter enum SystemModeEnum
        */
        enum SystemModeEnum {
            /**
            The Thermostat does not generate demand for Cooling or Heating
            */
            Off = 0,
            /**
            Demand is generated for either Cooling or Heating, as required
            */
            Auto = 1,
            /**
            Demand is only generated for Cooling
            */
            Cool = 3,
            /**
            Demand is only generated for Heating
            */
            Heat = 4,
            /**
            2nd stage heating is in use to achieve desired temperature
            */
            EmergencyHeat = 5,
            /**
            (see Terms)
            */
            Precooling = 6,
            FanOnly = 7,
            Dry = 8,
            Sleep = 9,
        }

        /**
        Matter enum TemperatureSetpointHoldEnum
        */
        enum TemperatureSetpointHoldEnum {
            /**
            Follow scheduling program
            */
            SetpointHoldOff = 0,
            /**
            Maintain current setpoint, regardless of schedule transitions
            */
            SetpointHoldOn = 1,
        }

        /**
        Matter enum ThermostatRunningModeEnum
        */
        enum ThermostatRunningModeEnum {
            /**
            The Thermostat does not generate demand for Cooling or Heating
            */
            Off = 0,
            /**
            Demand is only generated for Cooling
            */
            Cool = 3,
            /**
            Demand is only generated for Heating
            */
            Heat = 4,
        }

        /**
        Matter bitmap ACErrorCodeBitmap (map8)
        */
        [Flags]
        enum ACErrorCodeBitmap {
            /**
            Compressor Failure or Refrigerant Leakage
            */
            CompressorFail = 1,
            /**
            Room Temperature Sensor Failure
            */
            RoomSensorFail = 2,
            /**
            Outdoor Temperature Sensor Failure
            */
            OutdoorSensorFail = 4,
            /**
            Indoor Coil Temperature Sensor Failure
            */
            CoilSensorFail = 8,
            /**
            Fan Failure
            */
            FanFail = 16,
        }

        /**
        Matter bitmap HVACSystemTypeBitmap (map8)
        */
        [Flags]
        enum HVACSystemTypeBitmap {
            /**
            Stage of cooling the HVAC system is using. (bits 0..1)
            */
            CoolingStage = 3,
            /**
            Stage of heating the HVAC system is using. (bits 2..3)
            */
            HeatingStage = 12,
            /**
            Is the heating type Heat Pump.
            */
            HeatingIsHeatPump = 16,
            /**
            Does the HVAC system use fuel.
            */
            HeatingUsesFuel = 32,
        }

        // bitmap with a single field: AdHoc rejects one-member enums, kept as a constants container
        public struct OccupancyBitmap {
            /**
            Indicates the occupancy state
            */
            public const ulong Occupied = 1;
        }

        /**
        Matter bitmap PresetTypeFeaturesBitmap (map8)
        */
        [Flags]
        enum PresetTypeFeaturesBitmap {
            /**
            Preset may be automatically activated by the thermostat
            */
            Automatic = 1,
            /**
            Preset supports user-provided names
            */
            SupportsNames = 2,
        }

        /**
        Matter bitmap ProgrammingOperationModeBitmap (map8)
        */
        [Flags]
        enum ProgrammingOperationModeBitmap {
            /**
            Schedule programming mode. This enables any programmed weekly schedule configurations.
            */
            ScheduleActive = 1,
            /**
            Auto/recovery mode
            */
            AutoRecovery = 2,
            /**
            Economy/EnergyStar mode
            */
            Economy = 4,
        }

        /**
        Matter bitmap RelayStateBitmap (map8)
        */
        [Flags]
        enum RelayStateBitmap {
            /**
            Heat Stage On
            */
            Heat = 1,
            /**
            Cool Stage On
            */
            Cool = 2,
            /**
            Fan Stage On
            */
            Fan = 4,
            /**
            Heat 2nd Stage On
            */
            HeatStage2 = 8,
            /**
            Cool 2nd Stage On
            */
            CoolStage2 = 16,
            /**
            Fan 2nd Stage On
            */
            FanStage2 = 32,
            /**
            Fan 3rd Stage On
            */
            FanStage3 = 64,
        }

        /**
        Matter bitmap RemoteSensingBitmap (map8)
        */
        [Flags]
        enum RemoteSensingBitmap {
            /**
            Calculated Local Temperature is derived from a remote node
            */
            LocalTemperature = 1,
            /**
            OutdoorTemperature is derived from a remote node
            */
            OutdoorTemperature = 2,
            /**
            Occupancy is derived from a remote node
            */
            Occupancy = 4,
        }

        /**
        Matter bitmap ScheduleDayOfWeekBitmap (map8)
        */
        [Flags]
        enum ScheduleDayOfWeekBitmap {
            /**
            Sunday
            */
            Sunday = 1,
            /**
            Monday
            */
            Monday = 2,
            /**
            Tuesday
            */
            Tuesday = 4,
            /**
            Wednesday
            */
            Wednesday = 8,
            /**
            Thursday
            */
            Thursday = 16,
            /**
            Friday
            */
            Friday = 32,
            /**
            Saturday
            */
            Saturday = 64,
            /**
            Away or Vacation
            */
            Away = 128,
        }

        /**
        Matter bitmap ScheduleModeBitmap (map8)
        */
        [Flags]
        enum ScheduleModeBitmap {
            /**
            Adjust Heat Setpoint
            */
            HeatSetpointPresent = 1,
            /**
            Adjust Cool Setpoint
            */
            CoolSetpointPresent = 2,
        }

        /**
        Matter bitmap ScheduleTypeFeaturesBitmap (map8)
        */
        [Flags]
        enum ScheduleTypeFeaturesBitmap {
            /**
            Supports presets
            */
            SupportsPresets = 1,
            /**
            Supports setpoints
            */
            SupportsSetpoints = 2,
            /**
            Supports user-provided names
            */
            SupportsNames = 4,
            /**
            Supports transitioning to SystemModeOff
            */
            SupportsOff = 8,
        }

        /**
        Matter bitmap ThermostatSuggestionNotFollowingReasonBitmap (map8)
        */
        [Flags]
        enum ThermostatSuggestionNotFollowingReasonBitmap {
            /**
            Thermostat is responding to a Demand Response event
            */
            DemandResponseEvent = 1,
            /**
            Thermostat has an ongoing setpoint hold
            */
            OngoingHold = 2,
            /**
            Thermostat is following a schedule
            */
            Schedule = 4,
            /**
            Thermostat is following the occupancy signal
            */
            Occupancy = 8,
            /**
            Thermostat is set to Vacation mode
            */
            VacationMode = 16,
            /**
            Thermostat is following a Time Of Use based cost savings plan
            */
            TimeOfUseCostSavings = 32,
            /**
            Thermostat is precooling or preheating based on an energy forecast signal
            */
            PreCoolingOrPreHeating = 64,
            /**
            Thermostat has conflicting suggestions and is unable to choose one
            */
            ConflictingSuggestions = 128,
        }

        /**
        Matter struct PresetStruct
        */
        class PresetStruct {
            [D(16), FieldId(0x0), Quality("nullable"), Constraint("maxLength 16")] Binary[,,] PresetHandle;
            [FieldId(0x1)] PresetScenarioEnum PresetScenario;
            [D(+64), FieldId(0x2), Quality("nullable"), Default("null"), Constraint("maxLength 64"), Conformance("O")] string Name;
            [MatterType("temperature"), FieldId(0x3), Default("2600"), Constraint("desc"), Conformance("M[COOL]")] short? CoolingSetpoint;
            [MatterType("temperature"), FieldId(0x4), Default("2000"), Constraint("desc"), Conformance("M[HEAT]")] short? HeatingSetpoint;
            [FieldId(0x5), Quality("nullable"), Default("false")] bool? BuiltIn;
        }

        /**
        Matter struct PresetTypeStruct
        */
        class PresetTypeStruct {
            [FieldId(0x0)] PresetScenarioEnum PresetScenario;
            [FieldId(0x1), Default("0")] byte NumberOfPresets;
            [FieldId(0x2), Default("0")] PresetTypeFeaturesBitmap PresetTypeFeatures;
        }

        /**
        Matter struct ScheduleStruct
        */
        class ScheduleStruct {
            [D(16), FieldId(0x0), Quality("nullable"), Constraint("maxLength 16")] Binary[,,] ScheduleHandle;
            [FieldId(0x1), Constraint("desc")] SystemModeEnum SystemMode;
            [D(+64), FieldId(0x2), Constraint("maxLength 64"), Conformance("O")] string Name;
            [D(16), FieldId(0x3), Constraint("maxLength 16"), Conformance("O")] Binary[,,] PresetHandle;
            [MatterType("list<ScheduleTransitionStruct>"), FieldId(0x4), Default("empty"), Constraint("countBetween 1..attr:NumberOfScheduleTransitions")] ScheduleTransitionStruct[,,] Transitions; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
            [FieldId(0x5), Quality("nullable"), Default("false")] bool? BuiltIn;
        }

        /**
        Matter struct ScheduleTransitionStruct
        */
        class ScheduleTransitionStruct {
            [FieldId(0x0), Constraint("desc")] ScheduleDayOfWeekBitmap DayOfWeek;
            [MinMax(0, 1439), FieldId(0x1), Constraint("max 1439")] ushort TransitionTime;
            [D(16), FieldId(0x2), Constraint("maxLength 16"), Conformance("O[PRES]")] Binary[,,] PresetHandle;
            [FieldId(0x3), Constraint("desc"), Conformance("O")] SystemModeEnum? SystemMode;
            [MatterType("temperature"), FieldId(0x4), Constraint("desc"), Conformance("O[COOL]")] short? CoolingSetpoint;
            [MatterType("temperature"), FieldId(0x5), Constraint("desc"), Conformance("O[HEAT]")] short? HeatingSetpoint;
        }

        /**
        Matter struct ScheduleTypeStruct
        */
        class ScheduleTypeStruct {
            [FieldId(0x0), Constraint("desc")] SystemModeEnum SystemMode;
            [FieldId(0x1), Default("0"), Constraint("max attr:NumberOfSchedules")] byte NumberOfSchedules; // bounds depend on another attribute, cannot be bit-packed
            [FieldId(0x2), Default("0"), Constraint("desc")] ScheduleTypeFeaturesBitmap ScheduleTypeFeatures;
        }

        /**
        Matter struct SensorScheduleTransitionStruct
        */
        class SensorScheduleTransitionStruct {
            [FieldId(0x0), Constraint("desc")] ScheduleDayOfWeekBitmap DayOfWeek;
            [MinMax(0, 1439), FieldId(0x1), Constraint("max 1439")] ushort TransitionTime;
            [D(32), MatterType("list<octstr>"), FieldId(0x2), Constraint("maxCount 32")] octstr_max_16[,,] EnabledSensorHandles; // entry constraint: maxLength 16
        }

        /**
        Matter struct ThermostatSensorStruct
        */
        class ThermostatSensorStruct {
            [D(+64), FieldId(0x0), Constraint("maxLength 64")] string Name;
            [D(16), FieldId(0x1), Constraint("maxLength 16")] Binary[,,] SensorHandle;
            [MatterType("cluster-id"), FieldId(0x2)] uint Cluster;
            [MatterType("endpoint-no"), FieldId(0x3), Conformance("O")] ushort? Endpoint;
            [MatterType("node-id"), FieldId(0x4), Conformance("M[field:Endpoint]")] ulong? Node;
            [MatterType("fabric-idx"), FieldId(0x5), Conformance("M[field:Endpoint]")] byte? FabricIndex;
        }

        /**
        Matter struct ThermostatSuggestionStruct
        */
        class ThermostatSuggestionStruct {
            [FieldId(0x0)] byte UniqueID;
            [D(16), FieldId(0x1), Constraint("maxLength 16")] Binary[,,] PresetHandle;
            [FieldId(0x2)] DateTime EffectiveTime; // Matter epoch-s
            [FieldId(0x3)] DateTime ExpirationTime; // Matter epoch-s
        }

        /**
        Matter struct WeeklyScheduleTransitionStruct
        */
        class WeeklyScheduleTransitionStruct {
            [MinMax(0, 1439), FieldId(0x0), Constraint("max 1439")] ushort TransitionTime;
            [MatterType("temperature"), FieldId(0x1), Quality("nullable")] short? HeatSetpoint;
            [MatterType("temperature"), FieldId(0x2), Quality("nullable")] short? CoolSetpoint;
        }

        // octet string of up to 16 bytes, item type of list<octstr> fields
        class octstr_max_16 { [D(16)] Binary[,,] bytes; }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [MatterType("temperature"), AttrId(0x0), Access("read:view"), Quality("nullable")] short? LocalTemperature;
            [MatterType("temperature"), AttrId(0x1), Access("read:view"), Quality("nullable"), Default("null"), Conformance("O")] short? OutdoorTemperature;
            [MatterType("OccupancyBitmap"), AttrId(0x2), Access("read:view"), Conformance("M[OCC]")] byte? Occupancy; // values: constants container OccupancyBitmap
            [MatterType("temperature"), AttrId(0x3), Access("read:view"), Quality("fixed"), Default("700"), Constraint("desc"), Conformance("O[HEAT]")] short? AbsMinHeatSetpointLimit;
            [MatterType("temperature"), AttrId(0x4), Access("read:view"), Quality("fixed"), Default("3000"), Constraint("desc"), Conformance("O[HEAT]")] short? AbsMaxHeatSetpointLimit;
            [MatterType("temperature"), AttrId(0x5), Access("read:view"), Quality("fixed"), Default("1600"), Constraint("desc"), Conformance("O[COOL]")] short? AbsMinCoolSetpointLimit;
            [MatterType("temperature"), AttrId(0x6), Access("read:view"), Quality("fixed"), Default("3200"), Constraint("desc"), Conformance("O[COOL]")] short? AbsMaxCoolSetpointLimit;
            [MinMax(0, 100), AttrId(0x7), Access("read:view"), Constraint("between 0..100"), Conformance("X")] byte? PICoolingDemand;
            [MinMax(0, 100), AttrId(0x8), Access("read:view"), Constraint("between 0..100"), Conformance("X")] byte? PIHeatingDemand;
            [AttrId(0x9), Access("read:view write?:manage"), Conformance("X")] HVACSystemTypeBitmap? HVACSystemTypeConfiguration;
            [MatterType("SignedTemperature"), AttrId(0x10), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Conformance("O[!LTNE]")] sbyte? LocalTemperatureCalibration;
            [MatterType("temperature"), AttrId(0x11), Access("read:view write:operate"), Quality("nonVolatile"), Default("2600"), Constraint("desc"), Conformance("M[COOL]")] short? OccupiedCoolingSetpoint;
            [MatterType("temperature"), AttrId(0x12), Access("read:view write:operate"), Quality("nonVolatile"), Default("2000"), Constraint("desc"), Conformance("M[HEAT]")] short? OccupiedHeatingSetpoint;
            [MatterType("temperature"), AttrId(0x13), Access("read:view write:operate"), Quality("nonVolatile"), Default("2600"), Constraint("desc"), Conformance("M[(COOL&OCC)]")] short? UnoccupiedCoolingSetpoint;
            [MatterType("temperature"), AttrId(0x14), Access("read:view write:operate"), Quality("nonVolatile"), Default("2000"), Constraint("desc"), Conformance("M[(HEAT&OCC)]")] short? UnoccupiedHeatingSetpoint;
            [MatterType("temperature"), AttrId(0x15), Access("read:view write:manage"), Quality("nonVolatile"), Default("attr:AbsMinHeatSetpointLimit"), Constraint("desc"), Conformance("O[HEAT]")] short? MinHeatSetpointLimit;
            [MatterType("temperature"), AttrId(0x16), Access("read:view write:manage"), Quality("nonVolatile"), Default("attr:AbsMaxHeatSetpointLimit"), Constraint("desc"), Conformance("O[HEAT]")] short? MaxHeatSetpointLimit;
            [MatterType("temperature"), AttrId(0x17), Access("read:view write:manage"), Quality("nonVolatile"), Default("attr:AbsMinCoolSetpointLimit"), Constraint("desc"), Conformance("O[COOL]")] short? MinCoolSetpointLimit;
            [MatterType("temperature"), AttrId(0x18), Access("read:view write:manage"), Quality("nonVolatile"), Default("attr:AbsMaxCoolSetpointLimit"), Constraint("desc"), Conformance("O[COOL]")] short? MaxCoolSetpointLimit;
            [MatterType("SignedTemperature"), MinMax(0, 127), AttrId(0x19), Access("read:view write?:manage"), Quality("nonVolatile"), Default("20"), Constraint("between 0..127"), Conformance("M[AUTO]")] sbyte? MinSetpointDeadBand;
            [AttrId(0x1A), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Conformance("O")] RemoteSensingBitmap? RemoteSensing;
            [AttrId(0x1B), Access("read:view write:manage"), Quality("nonVolatile"), Constraint("desc")] ControlSequenceOfOperationEnum ControlSequenceOfOperation;
            [AttrId(0x1C), Access("read:view write:manage"), Quality("nonVolatile"), Constraint("desc")] SystemModeEnum SystemMode;
            [AttrId(0x1E), Access("read:view"), Default("0"), Constraint("desc"), Conformance("otherwise(M[(TEVT&AUTO)]; O[AUTO])")] ThermostatRunningModeEnum? ThermostatRunningMode;
            [AttrId(0x20), Access("read:view"), Quality("fixed"), Conformance("X")] StartOfWeekEnum? StartOfWeek;
            [AttrId(0x21), Access("read:view"), Quality("fixed"), Conformance("X")] byte? NumberOfWeeklyTransitions;
            [AttrId(0x22), Access("read:view"), Quality("fixed"), Conformance("X")] byte? NumberOfDailyTransitions;
            [AttrId(0x23), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Constraint("desc"), Conformance("O")] TemperatureSetpointHoldEnum? TemperatureSetpointHold;
            [MinMax(1, 1440), AttrId(0x24), Access("read:view write:manage"), Quality("nullable nonVolatile"), Default("null"), Constraint("between 1..1440"), Conformance("O")] ushort? TemperatureSetpointHoldDuration;
            [AttrId(0x25), Access("read:view write:manage"), Constraint("desc"), Conformance("X")] ProgrammingOperationModeBitmap? ThermostatProgrammingOperationMode;
            [AttrId(0x29), Access("read:view"), Constraint("desc"), Conformance("O")] RelayStateBitmap? ThermostatRunningState;
            [AttrId(0x30), Access("read:view"), Default("0"), Constraint("desc"), Conformance("O")] SetpointChangeSourceEnum? SetpointChangeSource;
            [MatterType("int16s"), AttrId(0x31), Access("read:view"), Quality("nullable"), Default("null"), Conformance("O")] short? SetpointChangeAmount;
            [AttrId(0x32), Access("read:view"), Default("MS"), Conformance("O")] DateTime? SetpointChangeSourceTimestamp; // Matter epoch-s
            [MatterType("UnsignedTemperature"), AttrId(0x34), Access("read:view write:manage"), Quality("nullable nonVolatile"), Constraint("between attr:OccupiedSetbackMin..attr:OccupiedSetbackMax"), Conformance("X")] byte? OccupiedSetback; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("UnsignedTemperature"), AttrId(0x35), Access("read:view"), Quality("nullable fixed"), Constraint("max attr:OccupiedSetbackMax"), Conformance("X")] byte? OccupiedSetbackMin; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("UnsignedTemperature"), AttrId(0x36), Access("read:view"), Quality("nullable fixed"), Constraint("between attr:OccupiedSetbackMin..254"), Conformance("X")] byte? OccupiedSetbackMax; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("UnsignedTemperature"), AttrId(0x37), Access("read:view write:manage"), Quality("nullable nonVolatile"), Constraint("between attr:UnoccupiedSetbackMin..attr:UnoccupiedSetbackMax"), Conformance("X")] byte? UnoccupiedSetback; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("UnsignedTemperature"), AttrId(0x38), Access("read:view"), Quality("nullable fixed"), Constraint("max attr:UnoccupiedSetbackMax"), Conformance("X")] byte? UnoccupiedSetbackMin; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("UnsignedTemperature"), AttrId(0x39), Access("read:view"), Quality("nullable fixed"), Constraint("between attr:UnoccupiedSetbackMin..254"), Conformance("X")] byte? UnoccupiedSetbackMax; // bounds depend on another attribute, cannot be bit-packed
            [MatterType("UnsignedTemperature"), AttrId(0x3A), Access("read:view write:manage"), Quality("nonVolatile"), Default("255"), Conformance("O")] byte? EmergencyHeatDelta;
            [AttrId(0x40), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Constraint("desc"), Conformance("O")] ACTypeEnum? ACType;
            [AttrId(0x41), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Conformance("O")] ushort? ACCapacity;
            [AttrId(0x42), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Constraint("desc"), Conformance("O")] ACRefrigerantTypeEnum? ACRefrigerantType;
            [AttrId(0x43), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Constraint("desc"), Conformance("O")] ACCompressorTypeEnum? ACCompressorType;
            [AttrId(0x44), Access("read:view write:manage"), Default("0"), Conformance("O")] ACErrorCodeBitmap? ACErrorCode;
            [AttrId(0x45), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Constraint("desc"), Conformance("O")] ACLouverPositionEnum? ACLouverPosition;
            [MatterType("temperature"), AttrId(0x46), Access("read:view"), Quality("nullable"), Default("null"), Conformance("O")] short? ACCoilTemperature;
            [MatterType("ACCapacityFormatEnum"), AttrId(0x47), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Constraint("desc"), Conformance("O")] byte? ACCapacityFormat; // values: constants container ACCapacityFormatEnum
            [D(7), MatterType("list<PresetTypeStruct>"), AttrId(0x48), Access("read:view"), Quality("fixed"), Constraint("countBetween 1..7"), Conformance("M[PRES]")] PresetTypeStruct[,,] PresetTypes;
            [D(3), MatterType("list<ScheduleTypeStruct>"), AttrId(0x49), Access("read:view"), Quality("fixed"), Constraint("countBetween 1..3"), Conformance("M[MSCH]")] ScheduleTypeStruct[,,] ScheduleTypes;
            [MinMax(1, 255), AttrId(0x4A), Access("read:view"), Quality("fixed"), Constraint("min 1"), Conformance("M[PRES]")] byte? NumberOfPresets;
            [MinMax(1, 255), AttrId(0x4B), Access("read:view"), Quality("fixed"), Constraint("min 1"), Conformance("M[MSCH]")] byte? NumberOfSchedules;
            [MinMax(1, 255), AttrId(0x4C), Access("read:view"), Quality("fixed"), Constraint("min 1"), Conformance("M[MSCH]")] byte? NumberOfScheduleTransitions;
            [MinMax(1, 255), AttrId(0x4D), Access("read:view"), Quality("nullable fixed"), Constraint("min 1"), Conformance("M[MSCH]")] byte? NumberOfScheduleTransitionPerDay;
            [D(16), AttrId(0x4E), Access("read:view"), Quality("nullable nonVolatile"), Constraint("maxLength 16"), Conformance("M[PRES]")] Binary[,,] ActivePresetHandle;
            [D(16), AttrId(0x4F), Access("read:view"), Quality("nullable nonVolatile"), Constraint("maxLength 16"), Conformance("M[MSCH]")] Binary[,,] ActiveScheduleHandle;
            [MatterType("list<PresetStruct>"), AttrId(0x50), Access("read:view write:manage"), Quality("nonVolatile atomicWrite"), Constraint("maxCount attr:NumberOfPresets"), Conformance("M[PRES]")] PresetStruct[,,] Presets; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
            [MatterType("list<ScheduleStruct>"), AttrId(0x51), Access("read:view write:manage"), Quality("nonVolatile atomicWrite"), Constraint("maxCount attr:NumberOfSchedules"), Conformance("M[MSCH]")] ScheduleStruct[,,] Schedules; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
            [AttrId(0x52), Access("read:view"), Quality("nullable nonVolatile"), Default("null"), Conformance("O")] DateTime? SetpointHoldExpiryTimestamp; // Matter epoch-s
            [MinMax(5, 255), AttrId(0x53), Access("read:view"), Quality("fixed"), Constraint("min 5"), Conformance("M[TSUGGEST]")] byte? MaxThermostatSuggestions;
            [MatterType("list<ThermostatSuggestionStruct>"), AttrId(0x54), Access("read:view"), Quality("nonVolatile"), Constraint("maxCount attr:MaxThermostatSuggestions"), Conformance("M[TSUGGEST]")] ThermostatSuggestionStruct[,,] ThermostatSuggestions; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
            [AttrId(0x55), Access("read:view"), Quality("nullable"), Conformance("M[TSUGGEST]")] ThermostatSuggestionStruct CurrentThermostatSuggestion;
            [AttrId(0x56), Access("read:view"), Quality("nullable"), Conformance("M[TSUGGEST]")] ThermostatSuggestionNotFollowingReasonBitmap? ThermostatSuggestionNotFollowingReason;
            [AttrId(0x57), Access("read:view"), Quality("nonVolatile"), Default("false"), Conformance("otherwise(P; O[HEAT])")] bool? CriticalFreezeProtection;
            [AttrId(0x58), Access("read:view"), Quality("nonVolatile"), Default("false"), Conformance("otherwise(P; O[COOL])")] bool? CriticalOverheatProtection;
            [D(32), MatterType("list<ThermostatSensorStruct>"), AttrId(0x59), Access("read:view"), Constraint("maxCount 32"), Conformance("otherwise(P; M[SENSORS])")] ThermostatSensorStruct[,,] Sensors;
            [D(32), MatterType("list<octstr>"), AttrId(0x5A), Access("read:view write:manage"), Quality("nonVolatile"), Constraint("maxCount 32"), Conformance("otherwise(P; M[SENSORS])")] octstr_max_16[,,] AvailableSensorHandles; // entry constraint: maxLength 16
            [D(32), MatterType("list<octstr>"), AttrId(0x5B), Access("read:view write:manage"), Quality("nonVolatile"), Constraint("maxCount 32"), Conformance("otherwise(P; M[SENSORS])")] octstr_max_16[,,] EnabledSensorHandles; // entry constraint: maxLength 16
            [AttrId(0x5C), Access("read:view"), Quality("fixed"), Conformance("otherwise(P; M[SENSORS])")] byte? NumberOfSensorScheduleTransitions;
            [MatterType("list<SensorScheduleTransitionStruct>"), AttrId(0x5D), Access("read:view write:manage"), Quality("nonVolatile atomicWrite"), Constraint("maxCount attr:NumberOfSensorScheduleTransitions"), Conformance("otherwise(P; M[SENSORS])")] SensorScheduleTransitionStruct[,,] SensorSchedule; // item count is bounded by another attribute; falls back to _DefaultMaxLengthOf.Arrays
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) SetpointRaiseLower (id 0x00)
        */
        class SetpointRaiseLower {
            public const uint command_id = 0x0;
            public const string access = "invoke:operate";
            public const string conformance = "M";
            [FieldId(0x0), Constraint("desc")] SetpointRaiseLowerModeEnum Mode;
            [FieldId(0x1)] sbyte Amount;
        }

        /**
        Matter response GetWeeklyScheduleResponse (id 0x00)
        */
        class GetWeeklyScheduleResponse {
            public const uint command_id = 0x0;
            public const string conformance = "X";
            [FieldId(0x0)] byte NumberOfTransitionsForSequence;
            [FieldId(0x1), Constraint("desc")] ScheduleDayOfWeekBitmap DayOfWeekForSequence;
            [FieldId(0x2), Constraint("desc")] ScheduleModeBitmap ModeForSequence;
            [D(10), MatterType("list<WeeklyScheduleTransitionStruct>"), FieldId(0x3), Constraint("maxCount 10")] WeeklyScheduleTransitionStruct[,,] Transitions;
        }

        /**
        Matter command (acknowledged with a status only) SetWeeklySchedule (id 0x01)
        */
        class SetWeeklySchedule {
            public const uint command_id = 0x1;
            public const string access = "invoke:manage";
            public const string conformance = "X";
            [FieldId(0x0)] byte NumberOfTransitionsForSequence;
            [FieldId(0x1), Constraint("desc")] ScheduleDayOfWeekBitmap DayOfWeekForSequence;
            [FieldId(0x2), Constraint("desc")] ScheduleModeBitmap ModeForSequence;
            [D(10), MatterType("list<WeeklyScheduleTransitionStruct>"), FieldId(0x3), Constraint("maxCount 10")] WeeklyScheduleTransitionStruct[,,] Transitions;
        }

        /**
        Matter request, answered by GetWeeklyScheduleResponse GetWeeklySchedule (id 0x02)
        */
        class GetWeeklyScheduleRequest {
            public const uint command_id = 0x2;
            public const string access = "invoke:operate";
            public const string conformance = "X";
            [FieldId(0x0), Constraint("desc")] ScheduleDayOfWeekBitmap DaysToReturn;
            [FieldId(0x1), Constraint("desc")] ScheduleModeBitmap ModeToReturn;
        }

        /**
        Matter response AddThermostatSuggestionResponse (id 0x02)
        */
        class AddThermostatSuggestionResponse {
            public const uint command_id = 0x2;
            public const string conformance = "M[TSUGGEST]";
            [FieldId(0x0)] byte UniqueID;
        }

        /**
        Matter command (acknowledged with a status only) ClearWeeklySchedule (id 0x03)
        */
        class ClearWeeklySchedule {
            public const uint command_id = 0x3;
            public const string access = "invoke:manage";
            public const string conformance = "X";
        }

        /**
        Matter command (acknowledged with a status only) SetActiveScheduleRequest (id 0x05)
        */
        class SetActiveScheduleRequest {
            public const uint command_id = 0x5;
            public const string access = "invoke:operate";
            public const string conformance = "M[MSCH]";
            [D(16), FieldId(0x0), Constraint("maxLength 16")] Binary[,,] ScheduleHandle;
        }

        /**
        Matter command (acknowledged with a status only) SetActivePresetRequest (id 0x06)
        */
        class SetActivePresetRequest {
            public const uint command_id = 0x6;
            public const string access = "invoke:operate";
            public const string conformance = "M[PRES]";
            [D(16), FieldId(0x0), Quality("nullable"), Constraint("maxLength 16")] Binary[,,] PresetHandle;
        }

        /**
        Matter request, answered by AddThermostatSuggestionResponse AddThermostatSuggestion (id 0x07)
        */
        class AddThermostatSuggestionRequest {
            public const uint command_id = 0x7;
            public const string access = "invoke:manage";
            public const string conformance = "M[TSUGGEST]";
            [D(16), FieldId(0x0), Constraint("maxLength 16")] Binary[,,] PresetHandle;
            [FieldId(0x1), Quality("nullable"), Constraint("desc")] DateTime? EffectiveTime; // Matter epoch-s
            [MinMax(30, 1440), FieldId(0x2), Constraint("between 30..1440")] ushort ExpirationInMinutes;
        }

        /**
        Matter command (acknowledged with a status only) RemoveThermostatSuggestion (id 0x08)
        */
        class RemoveThermostatSuggestion {
            public const uint command_id = 0x8;
            public const string access = "invoke:manage";
            public const string conformance = "M[TSUGGEST]";
            [FieldId(0x0)] byte UniqueID;
        }

        // ═════════════════════════ events ═════════════════════════

        /**
        Matter event SystemModeChange (id 0x00, priority info)
        */
        class SystemModeChange {
            public const uint event_id = 0x0;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[TEVT])";
            [FieldId(0x0), Conformance("O")] SystemModeEnum? PreviousSystemMode;
            [FieldId(0x1)] SystemModeEnum CurrentSystemMode;
        }

        /**
        Matter event LocalTemperatureChange (id 0x01, priority info)
        */
        class LocalTemperatureChange {
            public const uint event_id = 0x1;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[(TEVT&!LTNE)])";
            [MatterType("temperature"), FieldId(0x0), Quality("nullable")] short? CurrentLocalTemperature;
        }

        /**
        Matter event OccupancyChange (id 0x02, priority info)
        */
        class OccupancyChange {
            public const uint event_id = 0x2;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[(TEVT&OCC)])";
            [MatterType("OccupancyBitmap"), FieldId(0x0), Conformance("O")] byte? PreviousOccupancy; // values: constants container OccupancyBitmap
            [MatterType("OccupancyBitmap"), FieldId(0x1)] byte CurrentOccupancy; // values: constants container OccupancyBitmap
        }

        /**
        Matter event SetpointChange (id 0x03, priority info)
        */
        class SetpointChange {
            public const uint event_id = 0x3;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[TEVT])";
            [FieldId(0x0), Constraint("allowed Cool")] SystemModeEnum SystemMode;
            [MatterType("OccupancyBitmap"), FieldId(0x1), Default("1"), Conformance("M[OCC]")] byte? Occupancy; // values: constants container OccupancyBitmap
            [MatterType("temperature"), FieldId(0x2), Conformance("O")] short? PreviousSetpoint;
            [MatterType("temperature"), FieldId(0x3)] short CurrentSetpoint;
        }

        /**
        Matter event RunningStateChange (id 0x04, priority info)
        */
        class RunningStateChange {
            public const uint event_id = 0x4;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[TEVT])";
            [FieldId(0x0), Conformance("O")] RelayStateBitmap? PreviousRunningState;
            [FieldId(0x1)] RelayStateBitmap CurrentRunningState;
        }

        /**
        Matter event RunningModeChange (id 0x05, priority info)
        */
        class RunningModeChange {
            public const uint event_id = 0x5;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[(TEVT&AUTO)])";
            [FieldId(0x0), Conformance("O")] ThermostatRunningModeEnum? PreviousRunningMode;
            [FieldId(0x1)] ThermostatRunningModeEnum CurrentRunningMode;
        }

        /**
        Matter event ActiveScheduleChange (id 0x06, priority info)
        */
        class ActiveScheduleChange {
            public const uint event_id = 0x6;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[(TEVT&MSCH)])";
            [D(16), FieldId(0x0), Quality("nullable"), Constraint("maxLength 16"), Conformance("O")] Binary[,,] PreviousScheduleHandle;
            [D(16), FieldId(0x1), Quality("nullable"), Constraint("maxLength 16")] Binary[,,] CurrentScheduleHandle;
        }

        /**
        Matter event ActivePresetChange (id 0x07, priority info)
        */
        class ActivePresetChange {
            public const uint event_id = 0x7;
            public const string priority = "info";
            public const string access = "read:view";
            public const string conformance = "otherwise(P; M[(TEVT&PRES)])";
            [D(16), FieldId(0x0), Quality("nullable"), Constraint("maxLength 16"), Conformance("O")] Binary[,,] PreviousPresetHandle;
            [D(16), FieldId(0x1), Quality("nullable"), Constraint("maxLength 16")] Binary[,,] CurrentPresetHandle;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<(SetpointRaiseLower, SetWeeklySchedule, ClearWeeklySchedule, SetActiveScheduleRequest, SetActivePresetRequest, RemoveThermostatSuggestion)>]
            struct Invoke { }

            // commands with a data response: request/response calls initiated by the client
            (L____________, GetWeeklyScheduleResponse) GetWeeklySchedule(GetWeeklyScheduleRequest req);
            (L____________, AddThermostatSuggestionResponse) AddThermostatSuggestion(AddThermostatSuggestionRequest req);

            // events (and unreferenced responses) are reported by the server
            [____________r<(SystemModeChange, LocalTemperatureChange, OccupancyChange, SetpointChange, RunningStateChange, RunningModeChange, ActiveScheduleChange, ActivePresetChange)>]
            struct Report { }

            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
