// Generated by Matter2AdHoc (https://github.com/AdHoc-Protocol)
// Sources: WindowCovering.xml + globals
// Matter cluster Window Covering Cluster id 0x0102 revision 8
// Re-run the converter instead of editing this file by hand.

using System;
using org.unirail.Meta;

namespace org.matter {
    /**
        <see cref = 'Attributes'/>
        <see cref = 'DownOrClose'/>
        <see cref = 'GoToLiftPercentage'/>
        <see cref = 'GoToLiftValue'/>
        <see cref = 'GoToTiltPercentage'/>
        <see cref = 'GoToTiltValue'/>
        <see cref = 'StopMotion'/>
        <see cref = 'UpOrOpen'/>
    */
    public interface WindowCovering {

        enum _DefaultMaxLengthOf {
            Arrays  = 65_535,
            Maps    = 65_535,
            Sets    = 65_535,
            Strings = 65_535,
        }

        /**
        Matter cluster "Window Covering Cluster" (id 0x0102, revision 8).
        rev 1: Mandatory global ClusterRevision attribute added; CCB 1994 1995 1996 1997 2086 2094 2095 2096 2097
        rev 2: CCB 2328
        rev 3: CCB 2477 2555 2845 3028
        rev 4: All Hubs changes with FeatureMap &amp; OperationalStatus attribute
        rev 5: New data model format and notation. Created plus clarified PositionAware and AbsolutePosition features.
        General cleanup of functionality.
        rev 6: Marked AbsolutePosition feature and associated elements provisional.
        rev 7: Removed AbsolutePosition feature and all associated elements from the cluster.
        rev 8: Removed P quality.
        */
        public struct ClusterInfo {
            public const uint cluster_id = 0x102;
            public const string cluster_name = "Window Covering Cluster";
            public const uint revision = 8;
        }

        /**
        FeatureMap bits of the cluster.
        */
        [Flags]
        enum Features {
            /**
            Lift control and behavior for lifting/sliding window coverings (code LF)
            */
            Lift = 1,
            /**
            Tilt control and behavior for tilting window coverings (code TL)
            */
            Tilt = 2,
            /**
            Position aware lift control is supported. (code PA_LF)
            */
            PositionAwareLift = 4,
            /**
            (code ABS)
            */
            AbsolutePosition = 8,
            /**
            Position aware tilt control is supported. (code PA_TL)
            */
            PositionAwareTilt = 16,
        }

        /**
        Matter enum EndProductTypeEnum
        */
        enum EndProductTypeEnum {
            /**
            Simple Roller Shade
            */
            RollerShade = 0,
            /**
            Roman Shade
            */
            RomanShade = 1,
            /**
            Balloon Shade
            */
            BalloonShade = 2,
            /**
            Woven Wood
            */
            WovenWood = 3,
            /**
            Pleated Shade
            */
            PleatedShade = 4,
            /**
            Cellular Shade
            */
            CellularShade = 5,
            /**
            Layered Shade
            */
            LayeredShade = 6,
            /**
            Layered Shade 2D
            */
            LayeredShade2D = 7,
            /**
            Sheer Shade
            */
            SheerShade = 8,
            /**
            Tilt Only Interior Blind
            */
            TiltOnlyInteriorBlind = 9,
            /**
            Interior Blind
            */
            InteriorBlind = 10,
            /**
            Vertical Blind, Strip Curtain
            */
            VerticalBlindStripCurtain = 11,
            /**
            Interior Venetian Blind
            */
            InteriorVenetianBlind = 12,
            /**
            Exterior Venetian Blind
            */
            ExteriorVenetianBlind = 13,
            /**
            Lateral Left Curtain
            */
            LateralLeftCurtain = 14,
            /**
            Lateral Right Curtain
            */
            LateralRightCurtain = 15,
            /**
            Central Curtain
            */
            CentralCurtain = 16,
            /**
            Roller Shutter
            */
            RollerShutter = 17,
            /**
            Exterior Vertical Screen
            */
            ExteriorVerticalScreen = 18,
            /**
            Awning Terrace (Patio)
            */
            AwningTerracePatio = 19,
            /**
            Awning Vertical Screen
            */
            AwningVerticalScreen = 20,
            /**
            Tilt Only Pergola
            */
            TiltOnlyPergola = 21,
            /**
            Swinging Shutter
            */
            SwingingShutter = 22,
            /**
            Sliding Shutter
            */
            SlidingShutter = 23,
            /**
            Unknown
            */
            Unknown = 255,
        }

        /**
        Matter enum TypeEnum
        */
        enum TypeEnum {
            /**
            RollerShade
            */
            RollerShade = 0,
            /**
            RollerShade - 2 Motor
            */
            RollerShade2Motor = 1,
            /**
            RollerShade - Exterior
            */
            RollerShadeExterior = 2,
            /**
            RollerShade - Exterior - 2 Motor
            */
            RollerShadeExterior2Motor = 3,
            /**
            Drapery (curtain)
            */
            Drapery = 4,
            /**
            Awning
            */
            Awning = 5,
            /**
            Shutter
            */
            Shutter = 6,
            /**
            Tilt Blind - Tilt Only
            */
            TiltBlindTiltOnly = 7,
            /**
            Tilt Blind - Lift &amp; Tilt
            */
            TiltBlindLiftAndTilt = 8,
            /**
            Projector Screen
            */
            ProjectorScreen = 9,
            /**
            Unknown
            */
            Unknown = 255,
        }

        /**
        Matter bitmap ConfigStatusBitmap (map8)
        */
        [Flags]
        enum ConfigStatusBitmap {
            /**
            Device is operational.
            */
            Operational = 1,
            OnlineReserved = 2,
            /**
            The lift movement is reversed.
            */
            LiftMovementReversed = 4,
            /**
            Supports the PositionAwareLift feature (PA_LF).
            */
            LiftPositionAware = 8,
            /**
            Supports the PositionAwareTilt feature (PA_TL).
            */
            TiltPositionAware = 16,
            /**
            Uses an encoder for lift.
            */
            LiftEncoderControlled = 32,
            /**
            Uses an encoder for tilt.
            */
            TiltEncoderControlled = 64,
        }

        /**
        Matter bitmap ModeBitmap (map8)
        */
        [Flags]
        enum ModeBitmap {
            /**
            Reverse the lift direction.
            */
            MotorDirectionReversed = 1,
            /**
            Perform a calibration.
            */
            CalibrationMode = 2,
            /**
            Freeze all motions for maintenance.
            */
            MaintenanceMode = 4,
            /**
            Control the LEDs feedback.
            */
            LedFeedback = 8,
        }

        /**
        Matter bitmap OperationalStatusBitmap (map8)
        */
        [Flags]
        enum OperationalStatusBitmap {
            /**
            Global operational state. (bits 0..1)
            */
            Global = 3,
            /**
            Lift operational state. (bits 2..3)
            */
            Lift = 12,
            /**
            Tilt operational state. (bits 4..5)
            */
            Tilt = 48,
        }

        /**
        Matter bitmap SafetyStatusBitmap (map16)
        */
        [Flags]
        enum SafetyStatusBitmap {
            /**
            Movement commands are ignored (locked out). e.g. not granted authorization, outside some time/date range.
            */
            RemoteLockout = 1,
            /**
            Tampering detected on sensors or any other safety equipment. Ex: a device has been forcedly moved without its
            actuator(s).
            */
            TamperDetection = 2,
            /**
            Communication failure to sensors or other safety equipment.
            */
            FailedCommunication = 4,
            /**
            Device has failed to reach the desired position. e.g. with position aware device, time expired before
            TargetPosition is reached.
            */
            PositionFailure = 8,
            /**
            Motor(s) and/or electric circuit thermal protection activated.
            */
            ThermalProtection = 16,
            /**
            An obstacle is preventing actuator movement.
            */
            ObstacleDetected = 32,
            /**
            Device has power related issue or limitation e.g. device is running w/ the help of a backup battery or power
            might not be fully available at the moment.
            */
            Power = 64,
            /**
            Local safety sensor (not a direct obstacle) is preventing movements (e.g. Safety EU Standard EN60335).
            */
            StopInput = 128,
            /**
            Mechanical problem related to the motor(s) detected.
            */
            MotorJammed = 256,
            /**
            PCB, fuse and other electrics problems.
            */
            HardwareFailure = 512,
            /**
            Actuator is manually operated and is preventing actuator movement (e.g. actuator is disengaged/decoupled).
            */
            ManualOperation = 1024,
            /**
            Protection is activated.
            */
            Protection = 2048,
        }

        // ═════════════════════════ attributes ═════════════════════════

        /**
        All attributes of the cluster as one pack: the server reports them, the client writes the writable ones.
        */
        class Attributes {
            [AttrId(0x0), Access("read:view"), Quality("fixed"), Default("0"), Constraint("desc")] TypeEnum Type;
            [AttrId(0x1), Access("read:view"), Quality("fixed"), Conformance("X")] ushort? PhysicalClosedLimitLift;
            [AttrId(0x2), Access("read:view"), Quality("fixed"), Conformance("X")] ushort? PhysicalClosedLimitTilt;
            [AttrId(0x3), Access("read:view"), Quality("nullable nonVolatile"), Constraint("between attr:InstalledOpenLimitLift..attr:InstalledClosedLimitLift"), Conformance("X")] ushort? CurrentPositionLift; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x4), Access("read:view"), Quality("nullable nonVolatile"), Constraint("between attr:InstalledOpenLimitTilt..attr:InstalledClosedLimitTilt"), Conformance("X")] ushort? CurrentPositionTilt; // bounds depend on another attribute, cannot be bit-packed
            [AttrId(0x5), Access("read:view"), Quality("nonVolatile"), Default("0"), Conformance("O[LF]")] ushort? NumberOfActuationsLift;
            [AttrId(0x6), Access("read:view"), Quality("nonVolatile"), Default("0"), Conformance("O[TL]")] ushort? NumberOfActuationsTilt;
            [AttrId(0x7), Access("read:view"), Quality("nonVolatile"), Default("desc"), Constraint("desc")] ConfigStatusBitmap ConfigStatus;
            [MatterType("percent"), MinMax(0, 100), AttrId(0x8), Access("read:view"), Quality("nullable nonVolatile"), Default("null"), Conformance("O[(LF&PA_LF)]")] byte? CurrentPositionLiftPercentage;
            [MatterType("percent"), MinMax(0, 100), AttrId(0x9), Access("read:view"), Quality("nullable nonVolatile"), Default("null"), Conformance("O[(TL&PA_TL)]")] byte? CurrentPositionTiltPercentage;
            [AttrId(0xA), Access("read:view"), Default("0"), Constraint("max 63")] OperationalStatusBitmap OperationalStatus;
            [MatterType("percent100ths"), MinMax(0, 10000), AttrId(0xB), Access("read:view"), Quality("nullable"), Default("null"), Conformance("M[(LF&PA_LF)]")] ushort? TargetPositionLiftPercent100ths;
            [MatterType("percent100ths"), MinMax(0, 10000), AttrId(0xC), Access("read:view"), Quality("nullable"), Default("null"), Conformance("M[(TL&PA_TL)]")] ushort? TargetPositionTiltPercent100ths;
            [AttrId(0xD), Access("read:view"), Quality("fixed"), Default("0"), Constraint("desc")] EndProductTypeEnum EndProductType;
            [MatterType("percent100ths"), MinMax(0, 10000), AttrId(0xE), Access("read:view"), Quality("nullable nonVolatile"), Default("null"), Constraint("max 10000"), Conformance("M[(LF&PA_LF)]")] ushort? CurrentPositionLiftPercent100ths;
            [MatterType("percent100ths"), MinMax(0, 10000), AttrId(0xF), Access("read:view"), Quality("nullable nonVolatile"), Default("null"), Constraint("max 10000"), Conformance("M[(TL&PA_TL)]")] ushort? CurrentPositionTiltPercent100ths;
            [MinMax(0, 65534), AttrId(0x10), Access("read:view"), Quality("nonVolatile"), Constraint("max 65534"), Conformance("X")] ushort? InstalledOpenLimitLift;
            [MinMax(0, 65534), AttrId(0x11), Access("read:view"), Quality("nonVolatile"), Constraint("max 65534"), Conformance("X")] ushort? InstalledClosedLimitLift;
            [MinMax(0, 65534), AttrId(0x12), Access("read:view"), Quality("nonVolatile"), Constraint("max 65534"), Conformance("X")] ushort? InstalledOpenLimitTilt;
            [MinMax(0, 65534), AttrId(0x13), Access("read:view"), Quality("nonVolatile"), Constraint("max 65534"), Conformance("X")] ushort? InstalledClosedLimitTilt;
            [AttrId(0x17), Access("read:view write:manage"), Quality("nonVolatile"), Default("0"), Constraint("max 15")] ModeBitmap Mode;
            [AttrId(0x1A), Access("read:view"), Default("0"), Constraint("desc"), Conformance("O")] SafetyStatusBitmap? SafetyStatus;
        }

        // ═════════════════════════ commands ═════════════════════════

        /**
        Matter command (acknowledged with a status only) UpOrOpen (id 0x00)
        */
        class UpOrOpen {
            public const uint command_id = 0x0;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) DownOrClose (id 0x01)
        */
        class DownOrClose {
            public const uint command_id = 0x1;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) StopMotion (id 0x02)
        */
        class StopMotion {
            public const uint command_id = 0x2;
            public const string access = "invoke:operate";
            public const string conformance = "M";
        }

        /**
        Matter command (acknowledged with a status only) GoToLiftValue (id 0x04)
        */
        class GoToLiftValue {
            public const uint command_id = 0x4;
            public const string access = "invoke:operate";
            public const string conformance = "X";
            [FieldId(0x0), Constraint("desc")] ushort LiftValue;
        }

        /**
        Matter command (acknowledged with a status only) GoToLiftPercentage (id 0x05)
        */
        class GoToLiftPercentage {
            public const uint command_id = 0x5;
            public const string access = "invoke:operate";
            public const string conformance = "otherwise(M[(LF&PA_LF)]; O[LF])";
            [MatterType("percent100ths"), MinMax(0, 10000), FieldId(0x0), Constraint("desc")] ushort LiftPercent100thsValue;
        }

        /**
        Matter command (acknowledged with a status only) GoToTiltValue (id 0x07)
        */
        class GoToTiltValue {
            public const uint command_id = 0x7;
            public const string access = "invoke:operate";
            public const string conformance = "X";
            [FieldId(0x0), Constraint("desc")] ushort TiltValue;
        }

        /**
        Matter command (acknowledged with a status only) GoToTiltPercentage (id 0x08)
        */
        class GoToTiltPercentage {
            public const uint command_id = 0x8;
            public const string access = "invoke:operate";
            public const string conformance = "otherwise(M[(TL&PA_TL)]; O[TL])";
            [MatterType("percent100ths"), MinMax(0, 10000), FieldId(0x0), Constraint("desc")] ushort TiltPercent100thsValue;
        }

        // ═════════════════════════ topology ═════════════════════════

        // The Matter client / controller (invokes commands, reads and writes attributes, receives events).
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Client : Host { }

        // The Matter server / device that implements the cluster.
        /**
        <see cref = 'InTS'/>
        <see cref = 'InJAVA'/>
        <see cref = 'InCS'/>
        <see cref = 'InCPP'/>
        <see cref = 'InGO'/>
        <see cref = 'InRS'/>
        */
        struct Server : Host { }

        interface Interaction : Connects<Client, Server> {
            // commands acknowledged with a status only: fire-and-forget from the client
            [l____________<(UpOrOpen, DownOrClose, StopMotion, GoToLiftValue, GoToLiftPercentage, GoToTiltValue, GoToTiltPercentage)>]
            struct Invoke { }


            // attribute reads / writes / subscriptions carry the attributes pack in both directions
            [_____lr_____<Attributes>]
            struct AttributeAccess { }
        }

        // ═════════════════════════ Matter metadata attributes ═════════════════════════

        /** Matter field id inside a struct, command or event. */
        public class FieldIdAttribute : Attribute { public FieldIdAttribute(uint id) { } }

        /** Matter attribute id. */
        public class AttrIdAttribute : Attribute { public AttrIdAttribute(uint id) { } }

        /** Access as in the data model: read:&lt;privilege&gt; write:&lt;privilege&gt; invoke:&lt;privilege&gt; timed. */
        public class AccessAttribute : Attribute { public AccessAttribute(string access) { } }

        /** Qualities: nullable, fixed/nonVolatile persistence, scene, quieterReporting, atomicWrite. */
        public class QualityAttribute : Attribute { public QualityAttribute(string quality) { } }

        /** Default value as written in the data model. */
        public class DefaultAttribute : Attribute { public DefaultAttribute(string value) { } }

        /** The Matter type name when it is not a plain integer/string (semantic types, enum8, map8, list entry types...). */
        public class MatterTypeAttribute : Attribute { public MatterTypeAttribute(string type) { } }

        /** Constraint as written in the data model (max, between a..b, maxLength, allowed, attr:Name references, desc). */
        public class ConstraintAttribute : Attribute { public ConstraintAttribute(string constraint) { } }

        /** Conformance: M mandatory, O optional, P provisional, X obsolete/disallowed, [..] feature conditions, otherwise(..) chains. */
        public class ConformanceAttribute : Attribute { public ConformanceAttribute(string conformance) { } }

    }
}
